using System.Globalization;
using System.Text;

namespace Octokit.Generators;

internal static class IconCodeGenerator
{
	public static string Generate(
		IReadOnlyList<SvgIcon> icons,
		string targetNamespace,
		string className)
	{
		var builder = new StringBuilder();
		AppendLine(builder, "// <auto-generated />");
		AppendLine(builder, "// Generated by Octokit.Generators. Do not edit manually.");
		AppendLine(builder, "#nullable enable");
		AppendLine(builder);
		AppendLine(builder, "using System;");
		AppendLine(builder, "using Microsoft.UI.Xaml.Controls;");
		AppendLine(builder, "using Microsoft.UI.Xaml.Media;");
		AppendLine(builder, "using Windows.Foundation;");
		AppendLine(builder);
		AppendLine(builder, $"namespace {targetNamespace};");
		AppendLine(builder);
		AppendLine(builder, "public enum OcticonName");
		AppendLine(builder, "{");
		foreach (var icon in icons)
			AppendLine(builder, $"\t{icon.Identifier},");
		AppendLine(builder, "}");
		AppendLine(builder);
		AppendLine(builder, $"public static class {className}");
		AppendLine(builder, "{");
		AppendFactory(builder, "IconElement", "CreateIcon", icons, "Icon");
		AppendLine(builder);
		AppendFactory(builder, "IconSource", "CreateIconSource", icons, "Source");
		AppendLine(builder);
		AppendGeometryDispatch(builder, icons, "OcticonName");
		AppendLine(builder);
		AppendGeometryDispatch(builder, icons, "string");

		foreach (var icon in icons)
		{
			AppendLine(builder);
			AppendIconFactory(builder, icon);
			AppendLine(builder);
			AppendSourceFactory(builder, icon);
			AppendLine(builder);
			AppendGeometryFactory(builder, icon);
		}

		AppendLine(builder, "}");
		return builder.ToString().Replace("\n", "\r\n");
	}

	private static void AppendFactory(
		StringBuilder builder,
		string returnType,
		string methodName,
		IReadOnlyList<SvgIcon> icons,
		string methodSuffix)
	{
		AppendLine(builder, $"\tpublic static {returnType} {methodName}(OcticonName icon)");
		AppendLine(builder, "\t{");
		AppendLine(builder, "\t\treturn icon switch");
		AppendLine(builder, "\t\t{");
		foreach (var icon in icons)
			AppendLine(builder, $"\t\t\tOcticonName.{icon.Identifier} => Create{icon.Identifier}{methodSuffix}(),");
		AppendLine(builder, "\t\t\t_ => throw new ArgumentOutOfRangeException(nameof(icon), icon, null),");
		AppendLine(builder, "\t\t};");
		AppendLine(builder, "\t}");
	}

	private static void AppendIconFactory(StringBuilder builder, SvgIcon icon)
	{
		AppendLine(builder, $"\tprivate static IconElement Create{icon.Identifier}Icon()");
		AppendLine(builder, "\t{");
		AppendLine(builder, "\t\treturn new PathIcon");
		AppendLine(builder, "\t\t{");
		AppendLine(builder, $"\t\t\tWidth = {Number(icon.Width)},");
		AppendLine(builder, $"\t\t\tHeight = {Number(icon.Height)},");
		AppendLine(builder, $"\t\t\tData = Create{icon.Identifier}Geometry(),");
		AppendLine(builder, "\t\t};");
		AppendLine(builder, "\t}");
	}

	private static void AppendSourceFactory(StringBuilder builder, SvgIcon icon)
	{
		AppendLine(builder, $"\tprivate static IconSource Create{icon.Identifier}Source()");
		AppendLine(builder, "\t{");
		AppendLine(builder, "\t\treturn new PathIconSource");
		AppendLine(builder, "\t\t{");
		AppendLine(builder, $"\t\t\tData = Create{icon.Identifier}Geometry(),");
		AppendLine(builder, "\t\t};");
		AppendLine(builder, "\t}");
	}

	private static void AppendGeometryFactory(StringBuilder builder, SvgIcon icon)
	{
		AppendLine(builder, $"\tprivate static Geometry Create{icon.Identifier}Geometry()");
		AppendLine(builder, "\t{");
		AppendLine(builder, "\t\tvar geometry = new GeometryGroup");
		AppendLine(builder, "\t\t{");
		AppendLine(builder, "\t\t\tFillRule = FillRule.Nonzero,");
		AppendLine(builder, "\t\t};");

		for (var pathIndex = 0; pathIndex < icon.Paths.Count; pathIndex++)
		{
			var path = icon.Paths[pathIndex];
			AppendLine(builder);
			AppendLine(builder, $"\t\tvar path{pathIndex} = new PathGeometry");
			AppendLine(builder, "\t\t{");
			AppendLine(builder, $"\t\t\tFillRule = {FillRule(path.FillRule)},");
			AppendLine(builder, "\t\t\tFigures = new PathFigureCollection(),");
			AppendLine(builder, "\t\t};");

			for (var figureIndex = 0; figureIndex < path.Figures.Count; figureIndex++)
			{
				var figure = path.Figures[figureIndex];
				var variable = $"figure{pathIndex}_{figureIndex}";
				AppendLine(builder, $"\t\tvar {variable} = new PathFigure");
				AppendLine(builder, "\t\t{");
				AppendLine(builder, $"\t\t\tStartPoint = {Point(figure.StartPoint)},");
				AppendLine(builder, $"\t\t\tIsClosed = {Bool(figure.IsClosed)},");
				AppendLine(builder, "\t\t\tIsFilled = true,");
				AppendLine(builder, "\t\t\tSegments = new PathSegmentCollection(),");
				AppendLine(builder, "\t\t};");

				foreach (var segment in figure.Segments)
					AppendSegment(builder, variable, segment);

				AppendLine(builder, $"\t\tpath{pathIndex}.Figures.Add({variable});");
			}

			AppendLine(builder, $"\t\tgeometry.Children.Add(path{pathIndex});");
		}

		AppendLine(builder);
		AppendLine(builder, "\t\treturn geometry;");
		AppendLine(builder, "\t}");
	}

	private static void AppendGeometryDispatch(
		StringBuilder builder,
		IReadOnlyList<SvgIcon> icons,
		string parameterType)
	{
		var parameterName = parameterType == "string" ? "name" : "icon";
		AppendLine(builder, $"\tpublic static Geometry CreateGeometry({parameterType} {parameterName})");
		AppendLine(builder, "\t{");
		AppendLine(builder, $"\t\treturn {parameterName} switch");
		AppendLine(builder, "\t\t{");

		foreach (var icon in icons)
		{
			var value = parameterType == "string"
				? $"\"{icon.Identifier}\""
				: $"OcticonName.{icon.Identifier}";
			AppendLine(builder, $"\t\t\t{value} => Create{icon.Identifier}Geometry(),");
		}

		var exception = parameterType == "string"
			? "new ArgumentException($\"Unknown Octicon '{name}'.\", nameof(name))"
			: "new ArgumentOutOfRangeException(nameof(icon), icon, null)";
		AppendLine(builder, $"\t\t\t_ => throw {exception},");
		AppendLine(builder, "\t\t};");
		AppendLine(builder, "\t}");
	}

	private static void AppendSegment(StringBuilder builder, string figureVariable, SvgSegment segment)
	{
		var code = segment switch
		{
			SvgLineSegment line => $"new LineSegment {{ Point = {Point(line.Point)} }}",
			SvgBezierSegment bezier =>
				$"new BezierSegment {{ Point1 = {Point(bezier.Point1)}, Point2 = {Point(bezier.Point2)}, Point3 = {Point(bezier.Point3)} }}",
			SvgQuadraticBezierSegment quadratic =>
				$"new QuadraticBezierSegment {{ Point1 = {Point(quadratic.Point1)}, Point2 = {Point(quadratic.Point2)} }}",
			SvgArcSegment arc =>
				$"new ArcSegment {{ Size = new Size({Number(arc.RadiusX)}, {Number(arc.RadiusY)}), RotationAngle = {Number(arc.RotationAngle)}, IsLargeArc = {Bool(arc.IsLargeArc)}, SweepDirection = SweepDirection.{(arc.SweepClockwise ? "Clockwise" : "Counterclockwise")}, Point = {Point(arc.Point)} }}",
			_ => throw new InvalidOperationException($"Unsupported segment type {segment.GetType().Name}."),
		};

		AppendLine(builder, $"\t\t{figureVariable}.Segments.Add({code});");
	}

	private static string Point(SvgPoint point)
		=> $"new Point({Number(point.X)}, {Number(point.Y)})";

	private static string Number(double value)
	{
		if (Math.Abs(value) < 0.000000000001)
			value = 0;

		return value.ToString("0.####################", CultureInfo.InvariantCulture) + "d";
	}

	private static string Bool(bool value) => value ? "true" : "false";

	private static string FillRule(SvgFillRule fillRule)
		=> fillRule == SvgFillRule.EvenOdd ? "FillRule.EvenOdd" : "FillRule.Nonzero";

	private static void AppendLine(StringBuilder builder, string value = "")
		=> builder.Append(value).Append('\n');
}
