// Copyright (c) 0x5BFA. All rights reserved.
// Licensed under the MIT License. See the LICENSE.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Octokit.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class StringsPropertyGenerator : IIncrementalGenerator
{
	private const string ResourceFileSuffix = "en-US/Resources.resw";
	private const string ResourceNamespace = "FluentHub.Localization";

	private static readonly DiagnosticDescriptor InvalidResource = new(
		"FHL1001",
		"Resource file could not be parsed",
		"Resource file '{0}' could not be parsed: {1}",
		"FluentHub.Localization",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor InvalidResourceKey = new(
		"FHL1002",
		"Invalid resource key",
		"Resource key '{0}' in '{1}' must not contain a comma",
		"FluentHub.Localization",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor DuplicateResourceKey = new(
		"FHL1003",
		"Duplicate resource key",
		"Resource key '{0}' is declared more than once in '{1}'",
		"FluentHub.Localization",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	private static readonly DiagnosticDescriptor MultipleResourceFiles = new(
		"FHL1004",
		"Multiple English resource files detected",
		"Only one en-US Resources.resw file is supported, but multiple files were found",
		"FluentHub.Localization",
		DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var resourceFiles = context.AdditionalTextsProvider
			.Where(static file => IsEnglishResourceFile(file.Path));

		context.RegisterSourceOutput(resourceFiles, static (sourceContext, file) =>
			GenerateStrings(sourceContext, file));

		var resourcePaths = resourceFiles
			.Select(static (file, _) => file.Path)
			.Collect();

		context.RegisterSourceOutput(resourcePaths, static (sourceContext, paths) =>
			GenerateLocalizationExtensions(sourceContext, paths));
	}

	private static bool IsEnglishResourceFile(string path)
		=> path.Replace('\\', '/').EndsWith(ResourceFileSuffix, StringComparison.OrdinalIgnoreCase);

	private static void GenerateStrings(SourceProductionContext context, AdditionalText file)
	{
		if (!TryReadEntries(context, file, out var entries))
			return;

		var usedNames = new HashSet<string>(StringComparer.Ordinal);
		var builder = new StringBuilder(8000);
		builder.AppendLine("// <auto-generated />");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();
		builder.AppendLine($"namespace {ResourceNamespace};");
		builder.AppendLine();
		builder.AppendLine("public static partial class Strings");
		builder.AppendLine("{");

		foreach (var entry in entries)
		{
			var constantName = GetUniqueConstantName(entry.Key, usedNames);
			AppendDocumentation(builder, entry.Comment, entry.Value);
			builder.AppendLine($"\tpublic const string {constantName} = \"{EscapeStringLiteral(entry.Key)}\";");
		}

		builder.AppendLine("}");
		context.AddSource("Strings.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
	}

	private static void GenerateLocalizationExtensions(
		SourceProductionContext context,
		ImmutableArray<string> resourcePaths)
	{
		if (resourcePaths.IsDefaultOrEmpty)
			return;

		if (resourcePaths.Length > 1)
		{
			context.ReportDiagnostic(Diagnostic.Create(MultipleResourceFiles, Location.None));
			return;
		}

		var builder = new StringBuilder(2600);
		builder.AppendLine("// <auto-generated />");
		builder.AppendLine("#nullable enable");
		builder.AppendLine();
		builder.AppendLine($"namespace {ResourceNamespace};");
		builder.AppendLine();
		builder.AppendLine("public static partial class LocalizationExtensions");
		builder.AppendLine("{");
		builder.AppendLine("\tprivate static readonly global::Microsoft.Windows.ApplicationModel.Resources.ResourceMap? Resources =");
		builder.AppendLine("\t\tnew global::Microsoft.Windows.ApplicationModel.Resources.ResourceManager()");
		builder.AppendLine("\t\t\t.MainResourceMap");
		builder.AppendLine("\t\t\t.TryGetSubtree(\"Resources\");");
		builder.AppendLine();
		builder.AppendLine("\tprivate static readonly global::System.Collections.Concurrent.ConcurrentDictionary<string, string> LocalizedResources =");
		builder.AppendLine("\t\tnew(global::System.StringComparer.Ordinal);");
		builder.AppendLine();
		builder.AppendLine("\tpublic static string GetLocalized(this string resourceKey)");
		builder.AppendLine("\t{");
		builder.AppendLine("\t\tglobal::System.ArgumentException.ThrowIfNullOrWhiteSpace(resourceKey);");
		builder.AppendLine();
		builder.AppendLine("\t\tif (LocalizedResources.TryGetValue(resourceKey, out var value))");
		builder.AppendLine("\t\t\treturn value;");
		builder.AppendLine();
		builder.AppendLine("\t\tvar resourceMapKey = resourceKey.Replace('.', '/');");
		builder.AppendLine("\t\tvalue = Resources?.TryGetValue(resourceMapKey)?.ValueAsString ?? resourceKey;");
		builder.AppendLine("\t\treturn LocalizedResources.GetOrAdd(resourceKey, value);");
		builder.AppendLine("\t}");
		builder.AppendLine();
		builder.AppendLine("\tpublic static void ClearLocalizedCache() => LocalizedResources.Clear();");
		builder.AppendLine("}");

		context.AddSource(
			"LocalizationExtensions.g.cs",
			SourceText.From(builder.ToString(), Encoding.UTF8));
	}

	private static bool TryReadEntries(
		SourceProductionContext context,
		AdditionalText file,
		out IReadOnlyList<ResourceEntry> entries)
	{
		entries = [];

		try
		{
			var text = file.GetText(context.CancellationToken)?.ToString() ?? string.Empty;
			var document = XDocument.Parse(text, LoadOptions.PreserveWhitespace);
			var result = new List<ResourceEntry>();
			var keys = new HashSet<string>(StringComparer.Ordinal);

			foreach (var element in document.Descendants().Where(static element => element.Name.LocalName == "data"))
			{
				var key = element.Attribute("name")?.Value;
				if (string.IsNullOrWhiteSpace(key))
					continue;

				var resourceKey = key!;

				if (resourceKey.IndexOf(',') >= 0)
				{
					context.ReportDiagnostic(Diagnostic.Create(
						InvalidResourceKey,
						Location.None,
						resourceKey,
						file.Path));
					continue;
				}

				if (!keys.Add(resourceKey))
				{
					context.ReportDiagnostic(Diagnostic.Create(
						DuplicateResourceKey,
						Location.None,
						resourceKey,
						file.Path));
					continue;
				}

				result.Add(new ResourceEntry(
					resourceKey,
					element.Elements().FirstOrDefault(static child => child.Name.LocalName == "value")?.Value ?? string.Empty,
					element.Elements().FirstOrDefault(static child => child.Name.LocalName == "comment")?.Value));
			}

			entries = result.OrderBy(static entry => entry.Key, StringComparer.Ordinal).ToArray();
			return true;
		}
		catch (OperationCanceledException)
		{
			return false;
		}
		catch (Exception exception)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				InvalidResource,
				Location.None,
				file.Path,
				exception.Message));
			return false;
		}
	}

	private static void AppendDocumentation(StringBuilder builder, string? comment, string value)
	{
		if (comment is null && value.Length == 0)
			return;

		builder.AppendLine();
		builder.AppendLine("\t/// <summary>");
		if (!string.IsNullOrWhiteSpace(comment))
				builder.AppendLine($"\t/// {EscapeDocumentation(comment!)}");
		else
			builder.AppendLine("\t/// Gets the resource key.");
		builder.AppendLine("\t/// </summary>");
		if (value.Length > 0)
		{
			builder.AppendLine("\t/// <remarks>");
			builder.AppendLine($"\t/// e.g.: <b>{EscapeDocumentation(value)}</b>");
			builder.AppendLine("\t/// </remarks>");
		}
	}

	private static string GetUniqueConstantName(string resourceKey, HashSet<string> usedNames)
	{
		var baseName = GetConstantName(resourceKey);
		if (usedNames.Add(baseName))
			return baseName;

		for (var suffix = 2; ; suffix++)
		{
			var candidate = $"{baseName}_{suffix}";
			if (usedNames.Add(candidate))
				return candidate;
		}
	}

	private static string GetConstantName(string key)
	{
		var builder = new StringBuilder(key.Length + 1);
		foreach (var character in key)
		{
			if (builder.Length == 0)
			{
				if (SyntaxFacts.IsIdentifierStartCharacter(character))
					builder.Append(character);
				else if (SyntaxFacts.IsIdentifierPartCharacter(character))
					builder.Append('_').Append(character);
				else
					builder.Append('_');

				continue;
			}

			builder.Append(SyntaxFacts.IsIdentifierPartCharacter(character) ? character : '_');
		}

		if (builder.Length == 0)
			builder.Append("Resource");

		var result = builder.ToString();
		return SyntaxFacts.GetKeywordKind(result) is not SyntaxKind.None ||
			SyntaxFacts.GetContextualKeywordKind(result) is not SyntaxKind.None
			? $"_{result}"
			: result;
	}

	private static string EscapeDocumentation(string value)
		=> value
			.Replace("&", "&amp;")
			.Replace("<", "&lt;")
			.Replace(">", "&gt;")
			.Replace('\r', ' ')
			.Replace('\n', ' ');

	private static string EscapeStringLiteral(string value)
		=> value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n")
			.Replace("\t", "\\t");

	private sealed class ResourceEntry
	{
		public ResourceEntry(string key, string value, string? comment)
		{
			Key = key;
			Value = value;
			Comment = comment;
		}

		public string Key { get; }

		public string Value { get; }

		public string? Comment { get; }
	}
}
