name: Pull Request
description: Request pull for the FluentHub
body:
  - type: checkboxes
    attributes:
      label: Before you start...
      options:
        - label: Have you updated the FluentHub? You might be using an old version.
          required: true
        - label: Have you checked if similar issue have already been reported?
          required: true
  - type: textarea
    attributes:
      label: Resolved / Related Issues
      description: Items resolved/related issues by this PR.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details of Changes
      description: Add details of changes here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Validation
      description: How did you test these changes?
      options:
        - label: Built and ran the app
          required: true
        - label: Tested the changes for accessibility
          required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (screenshots, mockups) relevant to this feature request.
