<Project>

	<PropertyGroup>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<!--<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>-->
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

</Project>
