<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>Octokit</AssemblyName>
		<RootNamespace>Octokit</RootNamespace>
		<IsPackable>false</IsPackable>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<NoWarn>$(NoWarn);CS0618;CS0672;SYSLIB0051</NoWarn>
	</PropertyGroup>

</Project>
