namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of AcceptEnterpriseAdministratorInvitation
    /// </summary>
    public class AcceptEnterpriseAdministratorInvitationPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The invitation that was accepted.
        /// </summary>
        public EnterpriseAdministratorInvitation Invitation { get; set; }

        /// <summary>
        /// A message confirming the result of accepting an administrator invitation.
        /// </summary>
        public string Message { get; set; }
    }
}