namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AcceptEnterpriseAdministratorInvitation
    /// </summary>
    public class AcceptEnterpriseAdministratorInvitationInput
    {        /// <summary>
        /// The id of the invitation being accepted
        /// </summary>
        public ID InvitationId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}