namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of AcceptTopicSuggestion
    /// </summary>
    public class AcceptTopicSuggestionPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The accepted topic.
        /// </summary>
        public Topic Topic { get; set; }
    }
}