// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AddAssigneesToAssignable
	/// </summary>
	public class AddAssigneesToAssignableInput
	{
		/// <summary>
		/// The id of the assignable object to add assignees to.
		/// </summary>
		public ID AssignableId { get; set; }

		/// <summary>
		/// The id of users to add as assignees.
		/// </summary>
		public List<ID> AssigneeIds { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
