namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of AddAssigneesToAssignable
    /// </summary>
    public class AddAssigneesToAssignablePayload
    {
        /// <summary>
        /// The item that was assigned.
        /// </summary>
        public IAssignable Assignable { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}