namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of AddComment
    /// </summary>
    public class AddCommentPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The edge from the subject's comment connection.
        /// </summary>
        public IssueCommentEdge CommentEdge { get; set; }

        /// <summary>
        /// The subject
        /// </summary>
        public INode Subject { get; set; }

        /// <summary>
        /// The edge from the subject's timeline connection.
        /// </summary>
        public IssueTimelineItemEdge TimelineEdge { get; set; }
    }
}