namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddDiscussionPollVote
    /// </summary>
    public class AddDiscussionPollVoteInput
    {
        /// <summary>
        /// The Node ID of the discussion poll option to vote for.
        /// </summary>
        public ID PollOptionId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}