// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of AddEnterpriseSupportEntitlement
	/// </summary>
	public class AddEnterpriseSupportEntitlementPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// A message confirming the result of adding the support entitlement.
		/// </summary>
		public string Message { get; set; }
	}
}
