// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AddEnterpriseOrganizationMember
	/// </summary>
	public class AddEnterpriseOrganizationMemberInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the enterprise which owns the organization.
		/// </summary>
		public ID EnterpriseId { get; set; }

		/// <summary>
		/// The ID of the organization the users will be added to.
		/// </summary>
		public ID OrganizationId { get; set; }

		/// <summary>
		/// The IDs of the enterprise members to add.
		/// </summary>
		public List<ID> UserIds { get; set; }

		/// <summary>
		/// The role to assign the users in the organization
		/// </summary>
		public OrganizationMemberRole? Role { get; set; }
	}
}
