// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AddProjectColumn
	/// </summary>
	public class AddProjectColumnInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the project.
		/// </summary>
		public ID ProjectId { get; set; }

		/// <summary>
		/// The name of the column.
		/// </summary>
		public string Name { get; set; }
	}
}
