namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of AddProjectV2ItemById
    /// </summary>
    public class AddProjectV2ItemByIdPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The item added to the project.
        /// </summary>
        public ProjectV2Item Item { get; set; }
    }
}