namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of AddReaction
    /// </summary>
    public class AddReactionPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The reaction object.
        /// </summary>
        public Reaction Reaction { get; set; }

        /// <summary>
        /// The reaction groups for the subject.
        /// </summary>
        public List<ReactionGroup> ReactionGroups { get; set; }

        /// <summary>
        /// The reactable subject.
        /// </summary>
        public IReactable Subject { get; set; }
    }
}