// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of AddVerifiableDomain
	/// </summary>
	public class AddVerifiableDomainInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the owner to add the domain to
		/// </summary>
		public ID OwnerId { get; set; }

		/// <summary>
		/// The URL of the domain
		/// </summary>
		public string Domain { get; set; }
	}
}
