namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of ApproveDeployments
    /// </summary>
    public class ApproveDeploymentsPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The affected deployments.
        /// </summary>
        public List<Deployment> Deployments { get; set; }
    }
}