// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of ApproveDeployments
	/// </summary>
	public class ApproveDeploymentsInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The node ID of the workflow run containing the pending deployments.
		/// </summary>
		public ID WorkflowRunId { get; set; }

		/// <summary>
		/// The ids of environments to reject deployments
		/// </summary>
		public List<ID> EnvironmentIds { get; set; }

		/// <summary>
		/// Optional comment for approving deployments
		/// </summary>
		public string Comment { get; set; }
	}
}
