// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of ArchiveRepository
	/// </summary>
	public class ArchiveRepositoryPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The repository that was marked as archived.
		/// </summary>
		public Repository Repository { get; set; }
	}
}
