namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of ArchiveRepository
    /// </summary>
    public class ArchiveRepositoryPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The repository that was marked as archived.
        /// </summary>
        public Repository Repository { get; set; }
    }
}