namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of ArchiveProjectV2Item
    /// </summary>
    public class ArchiveProjectV2ItemPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The item archived from the project.
        /// </summary>
        public ProjectV2Item Item { get; set; }
    }
}