// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CancelEnterpriseAdminInvitation
	/// </summary>
	public class CancelEnterpriseAdminInvitationInput
	{
		/// <summary>
		/// The Node ID of the pending enterprise administrator invitation.
		/// </summary>
		public ID InvitationId { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
