namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of ChangeUserStatus
    /// </summary>
    public class ChangeUserStatusPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// Your updated status.
        /// </summary>
        public UserStatus Status { get; set; }
    }
}