// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of ClearLabelsFromLabelable
	/// </summary>
	public class ClearLabelsFromLabelableInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The id of the labelable object to clear the labels from.
		/// </summary>
		public ID LabelableId { get; set; }
	}
}
