// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of ClearLabelsFromLabelable
	/// </summary>
	public class ClearLabelsFromLabelablePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The item that was unlabeled.
		/// </summary>
		public ILabelable Labelable { get; set; }
	}
}
