// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of CloneProject
	/// </summary>
	public class CloneProjectPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The id of the JobStatus for populating cloned fields.
		/// </summary>
		public string JobStatusId { get; set; }

		/// <summary>
		/// The new cloned project.
		/// </summary>
		public Project Project { get; set; }
	}
}
