// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CloseIssue
	/// </summary>
	public class CloseIssueInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// ID of the issue to be closed.
		/// </summary>
		public ID IssueId { get; set; }

		/// <summary>
		/// The reason the issue is to be closed.
		/// </summary>
		public IssueClosedStateReason? StateReason { get; set; }
	}
}
