namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of CloseDiscussion
    /// </summary>
    public class CloseDiscussionPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The discussion that was closed.
        /// </summary>
        public Discussion Discussion { get; set; }
    }
}