namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of CreateProjectV2Field
    /// </summary>
    public class CreateProjectV2FieldPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The new field.
        /// </summary>
        public ProjectV2FieldConfiguration ProjectV2Field { get; set; }
    }
}