// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of CreateCheckRun
	/// </summary>
	public class CreateCheckRunPayload
	{
		/// <summary>
		/// The newly created check run.
		/// </summary>
		public CheckRun CheckRun { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
