namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateProjectV2
    /// </summary>
    public class CreateProjectV2Input
    {        /// <summary>
        /// The owner ID to create the project under.
        /// </summary>
        public ID OwnerId { get; set; }

        /// <summary>
        /// The title of the project.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}