namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateTeamDiscussion
    /// </summary>
    public class CreateTeamDiscussionInput
    {
        /// <summary>
        /// The ID of the team to which the discussion belongs.
        /// </summary>
        public ID TeamId { get; set; }

        /// <summary>
        /// The title of the discussion.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The content of the discussion.
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// If true, restricts the visibility of this discussion to team members and organization admins. If false or not specified, allows any organization member to view this discussion.
        /// </summary>
        public bool? Private { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}