// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of CreateCheckSuite
	/// </summary>
	public class CreateCheckSuitePayload
	{
		/// <summary>
		/// The newly created check suite.
		/// </summary>
		public CheckSuite CheckSuite { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
