namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of CreateCheckRun
    /// </summary>
    public class CreateCheckRunPayload
    {
        /// <summary>
        /// The newly created check run.
        /// </summary>
        public CheckRun CheckRun { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}