namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of CreateSponsorsListing
    /// </summary>
    public class CreateSponsorsListingPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The new GitHub Sponsors profile.
        /// </summary>
        public SponsorsListing SponsorsListing { get; set; }
    }
}