namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of CreateAttributionInvitation
    /// </summary>
    public class CreateAttributionInvitationPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The owner scoping the reattributable data.
        /// </summary>
        public Organization Owner { get; set; }

        /// <summary>
        /// The account owning the data to reattribute.
        /// </summary>
        public Claimable Source { get; set; }

        /// <summary>
        /// The account which may claim the data.
        /// </summary>
        public Claimable Target { get; set; }
    }
}