// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateLabel
	/// </summary>
	public class CreateLabelInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the repository.
		/// </summary>
		public ID RepositoryId { get; set; }

		/// <summary>
		/// A 6 character hex code, without the leading #, identifying the color of the label.
		/// </summary>
		public string Color { get; set; }

		/// <summary>
		/// The name of the label.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// A brief description of the label, such as its purpose.
		/// </summary>
		public string Description { get; set; }
	}
}
