// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of CreateDeploymentStatus
	/// </summary>
	public class CreateDeploymentStatusInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The node ID of the deployment.
		/// </summary>
		public ID DeploymentId { get; set; }

		/// <summary>
		/// The state of the deployment.
		/// </summary>
		public DeploymentStatusState State { get; set; }

		/// <summary>
		/// A short description of the status. Maximum length of 140 characters.
		/// </summary>
		public string Description { get; set; }

		/// <summary>
		/// If provided, updates the environment of the deploy. Otherwise, does not modify the environment.
		/// </summary>
		public string Environment { get; set; }

		/// <summary>
		/// Sets the URL for accessing your environment.
		/// </summary>
		public string EnvironmentUrl { get; set; }

		/// <summary>
		/// Adds a new inactive status to all non-transient, non-production environment deployments with the same repository and environment name as the created status's deployment.
		/// </summary>
		public bool? AutoInactive { get; set; }

		/// <summary>
		/// The log URL to associate with this status.       This URL should contain output to keep the user updated while the task is running       or serve as historical information for what happened in the deployment.
		/// </summary>
		public string LogUrl { get; set; }
	}
}
