// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of CreateIpAllowListEntry
	/// </summary>
	public class CreateIpAllowListEntryPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The IP allow list entry that was created.
		/// </summary>
		public IpAllowListEntry IpAllowListEntry { get; set; }
	}
}
