namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of CreateEnterpriseOrganization
    /// </summary>
    public class CreateEnterpriseOrganizationPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The enterprise that owns the created organization.
        /// </summary>
        public Enterprise Enterprise { get; set; }

        /// <summary>
        /// The organization that was created.
        /// </summary>
        public Organization Organization { get; set; }
    }
}