// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of DeclineTopicSuggestion
	/// </summary>
	public class DeclineTopicSuggestionInput
	{
		/// <summary>
		/// The Node ID of the repository.
		/// </summary>
		public ID RepositoryId { get; set; }

		/// <summary>
		/// The name of the suggested topic.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The reason why the suggested topic is declined.
		/// </summary>
		public TopicSuggestionDeclineReason Reason { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
