namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of DeleteVerifiableDomain
    /// </summary>
    public class DeleteVerifiableDomainPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The owning account from which the domain was deleted.
        /// </summary>
        public VerifiableDomainOwner Owner { get; set; }
    }
}