// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of DeleteProjectV2Item
	/// </summary>
	public class DeleteProjectV2ItemPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the deleted item.
		/// </summary>
		public ID? DeletedItemId { get; set; }
	}
}
