namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProjectCard
    /// </summary>
    public class DeleteProjectCardInput
    {
        /// <summary>
        /// The id of the card to delete.
        /// </summary>
        public ID CardId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}