namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteLinkedBranch
    /// </summary>
    public class DeleteLinkedBranchInput
    {
        /// <summary>
        /// The ID of the linked branch
        /// </summary>
        public ID LinkedBranchId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}