// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of DeleteLinkedBranch
	/// </summary>
	public class DeleteLinkedBranchPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The issue the linked branch was unlinked from.
		/// </summary>
		public Issue Issue { get; set; }
	}
}
