namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProjectColumn
    /// </summary>
    public class DeleteProjectColumnInput
    {
        /// <summary>
        /// The id of the column to delete.
        /// </summary>
        public ID ColumnId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}