namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of DeleteProjectColumn
    /// </summary>
    public class DeleteProjectColumnPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The deleted column ID.
        /// </summary>
        public ID? DeletedColumnId { get; set; }

        /// <summary>
        /// The project the deleted column was in.
        /// </summary>
        public Project Project { get; set; }
    }
}