// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of DeleteBranchProtectionRule
	/// </summary>
	public class DeleteBranchProtectionRuleInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The global relay id of the branch protection rule to be deleted.
		/// </summary>
		public ID BranchProtectionRuleId { get; set; }
	}
}
