// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of DeleteProjectV2Workflow
	/// </summary>
	public class DeleteProjectV2WorkflowPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the deleted workflow.
		/// </summary>
		public ID? DeletedWorkflowId { get; set; }

		/// <summary>
		/// The project the deleted workflow was in.
		/// </summary>
		public ProjectV2 ProjectV2 { get; set; }
	}
}
