namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of DeleteProject
    /// </summary>
    public class DeleteProjectPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The repository or organization the project was removed from.
        /// </summary>
        public IProjectOwner Owner { get; set; }
    }
}