namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProjectV2
    /// </summary>
    public class DeleteProjectV2Input
    {
        /// <summary>
        /// The ID of the Project to delete.
        /// </summary>
        public ID ProjectId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}