namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of DequeuePullRequest
    /// </summary>
    public class DequeuePullRequestPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The merge queue entry of the dequeued pull request.
        /// </summary>
        public MergeQueueEntry MergeQueueEntry { get; set; }
    }
}