namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of MarkPullRequestReadyForReview
    /// </summary>
    public class MarkPullRequestReadyForReviewPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The pull request that is ready for review.
        /// </summary>
        public PullRequest PullRequest { get; set; }
    }
}