namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of MinimizeComment
    /// </summary>
    public class MinimizeCommentPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The comment that was minimized.
        /// </summary>
        public IMinimizable MinimizedComment { get; set; }
    }
}