// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of PinEnvironment
	/// </summary>
	public class PinEnvironmentInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the environment to modify
		/// </summary>
		public ID EnvironmentId { get; set; }

		/// <summary>
		/// The desired state of the environment. If true, environment will be pinned. If false, it will be unpinned.
		/// </summary>
		public bool Pinned { get; set; }
	}
}
