namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RegenerateEnterpriseIdentityProviderRecoveryCodes
    /// </summary>
    public class RegenerateEnterpriseIdentityProviderRecoveryCodesInput
    {
        /// <summary>
        /// The ID of the enterprise on which to set an identity provider.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}