// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of RegenerateEnterpriseIdentityProviderRecoveryCodes
	/// </summary>
	public class RegenerateEnterpriseIdentityProviderRecoveryCodesInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the enterprise on which to set an identity provider.
		/// </summary>
		public ID EnterpriseId { get; set; }
	}
}
