// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of RemoveOutsideCollaborator
	/// </summary>
	public class RemoveOutsideCollaboratorInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the outside collaborator to remove.
		/// </summary>
		public ID UserId { get; set; }

		/// <summary>
		/// The ID of the organization to remove the outside collaborator from.
		/// </summary>
		public ID OrganizationId { get; set; }
	}
}
