namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RemoveReaction
    /// </summary>
    public class RemoveReactionInput
    {
        /// <summary>
        /// The Node ID of the subject to modify.
        /// </summary>
        public ID SubjectId { get; set; }

        /// <summary>
        /// The name of the emoji reaction to remove.
        /// </summary>
        public ReactionContent Content { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}