namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of RemoveEnterpriseIdentityProvider
    /// </summary>
    public class RemoveEnterpriseIdentityProviderPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The identity provider that was removed from the enterprise.
        /// </summary>
        public EnterpriseIdentityProvider IdentityProvider { get; set; }
    }
}