namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of RemoveEnterpriseSupportEntitlement
    /// </summary>
    public class RemoveEnterpriseSupportEntitlementPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// A message confirming the result of removing the support entitlement.
        /// </summary>
        public string Message { get; set; }
    }
}