// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of RemoveEnterpriseMember
	/// </summary>
	public class RemoveEnterpriseMemberPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The updated enterprise.
		/// </summary>
		public Enterprise Enterprise { get; set; }

		/// <summary>
		/// The user that was removed from the enterprise.
		/// </summary>
		public User User { get; set; }

		/// <summary>
		/// The viewer performing the mutation.
		/// </summary>
		public User Viewer { get; set; }
	}
}
