// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of RemoveStar
	/// </summary>
	public class RemoveStarInput
	{
		/// <summary>
		/// The Starrable ID to unstar.
		/// </summary>
		public ID StarrableId { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
