namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of RemoveAssigneesFromAssignable
    /// </summary>
    public class RemoveAssigneesFromAssignablePayload
    {
        /// <summary>
        /// The item that was unassigned.
        /// </summary>
        public IAssignable Assignable { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}