// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of ReorderEnvironment
	/// </summary>
	public class ReorderEnvironmentInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the environment to modify
		/// </summary>
		public ID EnvironmentId { get; set; }

		/// <summary>
		/// The desired position of the environment
		/// </summary>
		public int Position { get; set; }
	}
}
