// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of RequestReviews
	/// </summary>
	public class RequestReviewsPayload
	{
		/// <summary>
		/// Identifies the actor who performed the event.
		/// </summary>
		public IActor Actor { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The pull request that is getting requests.
		/// </summary>
		public PullRequest PullRequest { get; set; }

		/// <summary>
		/// The edge from the pull request to the requested reviewers.
		/// </summary>
		public UserEdge RequestedReviewersEdge { get; set; }
	}
}
