namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of RetireSponsorsTier
    /// </summary>
    public class RetireSponsorsTierInput
    {
        /// <summary>
        /// The ID of the published tier to retire.
        /// </summary>
        public ID TierId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}