namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of RevertPullRequest
    /// </summary>
    public class RevertPullRequestPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The pull request that was reverted.
        /// </summary>
        public PullRequest PullRequest { get; set; }

        /// <summary>
        /// The new pull request that reverts the input pull request.
        /// </summary>
        public PullRequest RevertPullRequest { get; set; }
    }
}