// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of SetUserInteractionLimit
	/// </summary>
	public class SetUserInteractionLimitPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The user that the interaction limit was set for.
		/// </summary>
		public User User { get; set; }
	}
}
