// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of TransferEnterpriseOrganization
	/// </summary>
	public class TransferEnterpriseOrganizationInput
	{
		/// <summary>
		/// The ID of the organization to transfer.
		/// </summary>
		public ID OrganizationId { get; set; }

		/// <summary>
		/// The ID of the enterprise where the organization should be transferred.
		/// </summary>
		public ID DestinationEnterpriseId { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
