// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UnarchiveProjectV2Item
	/// </summary>
	public class UnarchiveProjectV2ItemInput
	{
		/// <summary>
		/// The ID of the Project to archive the item from.
		/// </summary>
		public ID ProjectId { get; set; }

		/// <summary>
		/// The ID of the ProjectV2Item to unarchive.
		/// </summary>
		public ID ItemId { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
