// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of UnmarkProjectV2AsTemplate
	/// </summary>
	public class UnmarkProjectV2AsTemplatePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The project.
		/// </summary>
		public ProjectV2 ProjectV2 { get; set; }
	}
}
