// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UnmarkFileAsViewed
	/// </summary>
	public class UnmarkFileAsViewedInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the pull request.
		/// </summary>
		public ID PullRequestId { get; set; }

		/// <summary>
		/// The path of the file to mark as unviewed
		/// </summary>
		public string Path { get; set; }
	}
}
