// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of UnmarkIssueAsDuplicate
	/// </summary>
	public class UnmarkIssueAsDuplicatePayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The issue or pull request that was marked as a duplicate.
		/// </summary>
		public IssueOrPullRequest Duplicate { get; set; }
	}
}
