namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnminimizeComment
    /// </summary>
    public class UnminimizeCommentInput
    {        /// <summary>
        /// The Node ID of the subject to modify.
        /// </summary>
        public ID SubjectId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}