namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnpinIssue
    /// </summary>
    public class UnpinIssueInput
    {        /// <summary>
        /// The ID of the issue to be unpinned
        /// </summary>
        public ID IssueId { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}