// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateRepositoryWebCommitSignoffSetting
	/// </summary>
	public class UpdateRepositoryWebCommitSignoffSettingInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the repository to update.
		/// </summary>
		public ID RepositoryId { get; set; }

		/// <summary>
		/// Indicates if the repository should require signoff on web-based commits.
		/// </summary>
		public bool WebCommitSignoffRequired { get; set; }
	}
}
