// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of UpdateEnterpriseTwoFactorAuthenticationRequiredSetting
	/// </summary>
	public class UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The enterprise with the updated two factor authentication required setting.
		/// </summary>
		public Enterprise Enterprise { get; set; }

		/// <summary>
		/// A message confirming the result of updating the two factor authentication required setting.
		/// </summary>
		public string Message { get; set; }
	}
}
