namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateEnterpriseOwnerOrganizationRole
    /// </summary>
    public class UpdateEnterpriseOwnerOrganizationRoleInput
    {
        /// <summary>
        /// The ID of the Enterprise which the owner belongs to.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// The ID of the organization for membership change.
        /// </summary>
        public ID OrganizationId { get; set; }

        /// <summary>
        /// The role to assume in the organization.
        /// </summary>
        public RoleInOrganization OrganizationRole { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}