namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of UpdateTeamDiscussionComment
    /// </summary>
    public class UpdateTeamDiscussionCommentPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The updated comment.
        /// </summary>
        public TeamDiscussionComment TeamDiscussionComment { get; set; }
    }
}