// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateEnterpriseMembersCanMakePurchasesSetting
	/// </summary>
	public class UpdateEnterpriseMembersCanMakePurchasesSettingInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the enterprise on which to set the members can make purchases setting.
		/// </summary>
		public ID EnterpriseId { get; set; }

		/// <summary>
		/// The value for the members can make purchases setting on the enterprise.
		/// </summary>
		public EnterpriseMembersCanMakePurchasesSettingValue SettingValue { get; set; }
	}
}
