namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateIpAllowListForInstalledAppsEnabledSetting
    /// </summary>
    public class UpdateIpAllowListForInstalledAppsEnabledSettingInput
    {
        /// <summary>
        /// The ID of the owner.
        /// </summary>
        public ID OwnerId { get; set; }

        /// <summary>
        /// The value for the IP allow list configuration for installed GitHub Apps setting.
        /// </summary>
        public IpAllowListForInstalledAppsEnabledSettingValue SettingValue { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}