// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateRefs
	/// </summary>
	public class UpdateRefsInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The Node ID of the repository.
		/// </summary>
		public ID RepositoryId { get; set; }

		/// <summary>
		/// A list of ref updates.
		/// </summary>
		public List<RefUpdate> RefUpdates { get; set; }
	}
}
