namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of UpdateIpAllowListEnabledSetting
    /// </summary>
    public class UpdateIpAllowListEnabledSettingPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The IP allow list owner on which the setting was updated.
        /// </summary>
        public IpAllowListOwner Owner { get; set; }
    }
}