// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateEnterpriseAllowPrivateRepositoryForkingSetting
	/// </summary>
	public class UpdateEnterpriseAllowPrivateRepositoryForkingSettingInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the enterprise on which to set the allow private repository forking setting.
		/// </summary>
		public ID EnterpriseId { get; set; }

		/// <summary>
		/// The value for the allow private repository forking setting on the enterprise.
		/// </summary>
		public EnterpriseEnabledDisabledSettingValue SettingValue { get; set; }

		/// <summary>
		/// The value for the allow private repository forking policy on the enterprise.
		/// </summary>
		public EnterpriseAllowPrivateRepositoryForkingPolicyValue? PolicyValue { get; set; }
	}
}
