// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateRepositoryRuleset
	/// </summary>
	public class UpdateRepositoryRulesetInput
	{
		/// <summary>
		/// The global relay id of the repository ruleset to be updated.
		/// </summary>
		public ID RepositoryRulesetId { get; set; }

		/// <summary>
		/// The name of the ruleset.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The target of the ruleset.
		/// </summary>
		public RepositoryRulesetTarget? Target { get; set; }

		/// <summary>
		/// The list of rules for this ruleset
		/// </summary>
		public List<RepositoryRuleInput> Rules { get; set; }

		/// <summary>
		/// The list of conditions for this ruleset
		/// </summary>
		public RepositoryRuleConditionsInput Conditions { get; set; }

		/// <summary>
		/// The enforcement level for this ruleset
		/// </summary>
		public RuleEnforcement? Enforcement { get; set; }

		/// <summary>
		/// A list of actors that are allowed to bypass rules in this ruleset.
		/// </summary>
		public List<RepositoryRulesetBypassActorInput> BypassActors { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
