// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateOrganizationWebCommitSignoffSetting
	/// </summary>
	public class UpdateOrganizationWebCommitSignoffSettingInput
	{
		/// <summary>
		/// The ID of the organization on which to set the web commit signoff setting.
		/// </summary>
		public ID OrganizationId { get; set; }

		/// <summary>
		/// Enable signoff on web-based commits for repositories in the organization?
		/// </summary>
		public bool WebCommitSignoffRequired { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
