// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateProjectV2DraftIssue
	/// </summary>
	public class UpdateProjectV2DraftIssueInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the draft issue to update.
		/// </summary>
		public ID DraftIssueId { get; set; }

		/// <summary>
		/// The title of the draft issue.
		/// </summary>
		public string Title { get; set; }

		/// <summary>
		/// The body of the draft issue.
		/// </summary>
		public string Body { get; set; }

		/// <summary>
		/// The IDs of the assignees of the draft issue.
		/// </summary>
		public List<ID> AssigneeIds { get; set; }
	}
}
