// Copyright (c) 2022-2024 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateProject
	/// </summary>
	public class UpdateProjectInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The Project ID to update.
		/// </summary>
		public ID ProjectId { get; set; }

		/// <summary>
		/// The name of project.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The description of project.
		/// </summary>
		public string Body { get; set; }

		/// <summary>
		/// Whether the project is open or closed.
		/// </summary>
		public ProjectState? State { get; set; }

		/// <summary>
		/// Whether the project is public or not.
		/// </summary>
		public bool? Public { get; set; }
	}
}
