// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of UpdateTeamDiscussion
	/// </summary>
	public class UpdateTeamDiscussionPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The updated discussion.
		/// </summary>
		public TeamDiscussion TeamDiscussion { get; set; }
	}
}
