// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateIssueComment
	/// </summary>
	public class UpdateIssueCommentInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ID of the IssueComment to modify.
		/// </summary>
		public ID Id { get; set; }

		/// <summary>
		/// The updated text of the comment.
		/// </summary>
		public string Body { get; set; }
	}
}
