namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of UpdateSubscription
    /// </summary>
    public class UpdateSubscriptionPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The input subscribable entity.
        /// </summary>
        public ISubscribable Subscribable { get; set; }
    }
}