namespace FluentHub.Octokit.v4.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdatePullRequestBranch
    /// </summary>
    public class UpdatePullRequestBranchInput
    {
        /// <summary>
        /// The Node ID of the pull request.
        /// </summary>
        public ID PullRequestId { get; set; }

        /// <summary>
        /// The head ref oid for the upstream branch.
        /// </summary>
        public string ExpectedHeadOid { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}