namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of UpdateEnterpriseAllowPrivateRepositoryForkingSetting
    /// </summary>
    public class UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The enterprise with the updated allow private repository forking setting.
        /// </summary>
        public Enterprise Enterprise { get; set; }

        /// <summary>
        /// A message confirming the result of updating the allow private repository forking setting.
        /// </summary>
        public string Message { get; set; }
    }
}