namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of UpdateProjectV2DraftIssue
    /// </summary>
    public class UpdateProjectV2DraftIssuePayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The draft issue updated in the project.
        /// </summary>
        public DraftIssue DraftIssue { get; set; }
    }
}