// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateProjectCard
	/// </summary>
	public class UpdateProjectCardInput
	{
		/// <summary>
		/// The ProjectCard ID to update.
		/// </summary>
		public ID ProjectCardId { get; set; }

		/// <summary>
		/// Whether or not the ProjectCard should be archived
		/// </summary>
		public bool? IsArchived { get; set; }

		/// <summary>
		/// The note of ProjectCard.
		/// </summary>
		public string Note { get; set; }

		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }
	}
}
