namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    /// <summary>
    /// Autogenerated return type of UpdateIpAllowListEntry
    /// </summary>
    public class UpdateIpAllowListEntryPayload
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The IP allow list entry that was updated.
        /// </summary>
        public IpAllowListEntry IpAllowListEntry { get; set; }
    }
}