// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated input type of UpdateProjectColumn
	/// </summary>
	public class UpdateProjectColumnInput
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The ProjectColumn ID to update.
		/// </summary>
		public ID ProjectColumnId { get; set; }

		/// <summary>
		/// The name of project column.
		/// </summary>
		public string Name { get; set; }
	}
}
