namespace FluentHub.Octokit.Models.v4
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateRepositoryWebCommitSignoffSetting
    /// </summary>
    public class UpdateRepositoryWebCommitSignoffSettingInput
    {
        /// <summary>
        /// The ID of the repository to update.
        /// </summary>
        public ID RepositoryId { get; set; }

        /// <summary>
        /// Indicates if the repository should require signoff on web-based commits.
        /// </summary>
        public bool WebCommitSignoffRequired { get; set; }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }
    }
}