// Copyright (c) 2023 0x5BFA
// Licensed under the MIT License. See the LICENSE.

namespace FluentHub.Octokit.Models.v4
{
	/// <summary>
	/// Autogenerated return type of VerifyVerifiableDomain
	/// </summary>
	public class VerifyVerifiableDomainPayload
	{
		/// <summary>
		/// A unique identifier for the client performing the mutation.
		/// </summary>
		public string ClientMutationId { get; set; }

		/// <summary>
		/// The verifiable domain that was verified.
		/// </summary>
		public VerifiableDomain Domain { get; set; }
	}
}
