namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AbortRepositoryMigration
    /// </summary>
    public class AbortRepositoryMigrationInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the migration to be aborted.
        /// </summary>
        public ID MigrationId { get; set; }
    }
}