namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AbortQueuedMigrations
    /// </summary>
    public class AbortQueuedMigrationsInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the organization that is running the migrations.
        /// </summary>
        public ID OwnerId { get; set; }
    }
}