namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of AcceptEnterpriseAdministratorInvitation
    /// </summary>
    public class AcceptEnterpriseAdministratorInvitationPayload : QueryableValue<AcceptEnterpriseAdministratorInvitationPayload>
    {
        internal AcceptEnterpriseAdministratorInvitationPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The invitation that was accepted.
        /// </summary>
        public EnterpriseAdministratorInvitation Invitation => this.CreateProperty(x => x.Invitation, Octokit.GraphQL.Model.EnterpriseAdministratorInvitation.Create);

        /// <summary>
        /// A message confirming the result of accepting an administrator invitation.
        /// </summary>
        public string Message { get; }

        internal static AcceptEnterpriseAdministratorInvitationPayload Create(Expression expression)
        {
            return new AcceptEnterpriseAdministratorInvitationPayload(expression);
        }
    }
}