namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of AddAssigneesToAssignable
    /// </summary>
    public class AddAssigneesToAssignableInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The id of the assignable object to add assignees to.
        /// </summary>
        public ID AssignableId { get; set; }

        /// <summary>
        /// The id of users to add as assignees.
        /// </summary>
        public IEnumerable<ID> AssigneeIds { get; set; }
    }
}