namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CancelSponsorship
    /// </summary>
    public class CancelSponsorshipInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the user or organization who is acting as the sponsor, paying for the sponsorship. Required if sponsorLogin is not given.
        /// </summary>
        public ID? SponsorId { get; set; }

        /// <summary>
        /// The username of the user or organization who is acting as the sponsor, paying for the sponsorship. Required if sponsorId is not given.
        /// </summary>
        public string SponsorLogin { get; set; }

        /// <summary>
        /// The ID of the user or organization who is receiving the sponsorship. Required if sponsorableLogin is not given.
        /// </summary>
        public ID? SponsorableId { get; set; }

        /// <summary>
        /// The username of the user or organization who is receiving the sponsorship. Required if sponsorableId is not given.
        /// </summary>
        public string SponsorableLogin { get; set; }
    }
}