namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CancelSponsorship
    /// </summary>
    public class CancelSponsorshipPayload : QueryableValue<CancelSponsorshipPayload>
    {
        internal CancelSponsorshipPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The tier that was being used at the time of cancellation.
        /// </summary>
        public SponsorsTier SponsorsTier => this.CreateProperty(x => x.SponsorsTier, Octokit.GraphQL.Model.SponsorsTier.Create);

        internal static CancelSponsorshipPayload Create(Expression expression)
        {
            return new CancelSponsorshipPayload(expression);
        }
    }
}