namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ClearProjectV2ItemFieldValue
    /// </summary>
    public class ClearProjectV2ItemFieldValuePayload : QueryableValue<ClearProjectV2ItemFieldValuePayload>
    {
        internal ClearProjectV2ItemFieldValuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated item.
        /// </summary>
        public ProjectV2Item ProjectV2Item => this.CreateProperty(x => x.ProjectV2Item, Octokit.GraphQL.Model.ProjectV2Item.Create);

        internal static ClearProjectV2ItemFieldValuePayload Create(Expression expression)
        {
            return new ClearProjectV2ItemFieldValuePayload(expression);
        }
    }
}