namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CloneTemplateRepository
    /// </summary>
    public class CloneTemplateRepositoryPayload : QueryableValue<CloneTemplateRepositoryPayload>
    {
        internal CloneTemplateRepositoryPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The new repository.
        /// </summary>
        public Repository Repository => this.CreateProperty(x => x.Repository, Octokit.GraphQL.Model.Repository.Create);

        internal static CloneTemplateRepositoryPayload Create(Expression expression)
        {
            return new CloneTemplateRepositoryPayload(expression);
        }
    }
}