namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ClosePullRequest
    /// </summary>
    public class ClosePullRequestPayload : QueryableValue<ClosePullRequestPayload>
    {
        internal ClosePullRequestPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The pull request that was closed.
        /// </summary>
        public PullRequest PullRequest => this.CreateProperty(x => x.PullRequest, Octokit.GraphQL.Model.PullRequest.Create);

        internal static ClosePullRequestPayload Create(Expression expression)
        {
            return new ClosePullRequestPayload(expression);
        }
    }
}