namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CopyProjectV2
    /// </summary>
    public class CopyProjectV2Input
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the source Project to copy.
        /// </summary>
        public ID ProjectId { get; set; }

        /// <summary>
        /// The owner ID of the new project.
        /// </summary>
        public ID OwnerId { get; set; }

        /// <summary>
        /// The title of the project.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Include draft issues in the new project
        /// </summary>
        public bool? IncludeDraftIssues { get; set; }
    }
}