namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateIssue
    /// </summary>
    public class CreateIssueInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the repository.
        /// </summary>
        public ID RepositoryId { get; set; }

        /// <summary>
        /// The title for the issue.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The body for the issue description.
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// The Node ID for the user assignee for this issue.
        /// </summary>
        public IEnumerable<ID> AssigneeIds { get; set; }

        /// <summary>
        /// The Node ID of the milestone for this issue.
        /// </summary>
        public ID? MilestoneId { get; set; }

        /// <summary>
        /// An array of Node IDs of labels for this issue.
        /// </summary>
        public IEnumerable<ID> LabelIds { get; set; }

        /// <summary>
        /// An array of Node IDs for projects associated with this issue.
        /// </summary>
        public IEnumerable<ID> ProjectIds { get; set; }

        /// <summary>
        /// The name of an issue template in the repository, assigns labels and assignees from the template to the issue
        /// </summary>
        public string IssueTemplate { get; set; }
    }
}