namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateEnterpriseOrganization
    /// </summary>
    public class CreateEnterpriseOrganizationInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the enterprise owning the new organization.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// The login of the new organization.
        /// </summary>
        public string Login { get; set; }

        /// <summary>
        /// The profile name of the new organization.
        /// </summary>
        public string ProfileName { get; set; }

        /// <summary>
        /// The email used for sending billing receipts.
        /// </summary>
        public string BillingEmail { get; set; }

        /// <summary>
        /// The logins for the administrators of the new organization.
        /// </summary>
        public IEnumerable<string> AdminLogins { get; set; }
    }
}