namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateAttributionInvitation
    /// </summary>
    public class CreateAttributionInvitationInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the owner scoping the reattributable data.
        /// </summary>
        public ID OwnerId { get; set; }

        /// <summary>
        /// The Node ID of the account owning the data to reattribute.
        /// </summary>
        public ID SourceId { get; set; }

        /// <summary>
        /// The Node ID of the account which may claim the data.
        /// </summary>
        public ID TargetId { get; set; }
    }
}