namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of CreateTeamDiscussion
    /// </summary>
    public class CreateTeamDiscussionInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the team to which the discussion belongs. This field is required.
        /// **Upcoming Change on 2024-07-01 UTC**
        /// **Description:** `teamId` will be removed. Follow the guide at https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/ to find a suitable replacement.
        /// **Reason:** The Team Discussions feature is deprecated in favor of Organization Discussions.
        /// </summary>
        public ID? TeamId { get; set; }

        /// <summary>
        /// The title of the discussion. This field is required.
        /// **Upcoming Change on 2024-07-01 UTC**
        /// **Description:** `title` will be removed. Follow the guide at https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/ to find a suitable replacement.
        /// **Reason:** The Team Discussions feature is deprecated in favor of Organization Discussions.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The content of the discussion. This field is required.
        /// **Upcoming Change on 2024-07-01 UTC**
        /// **Description:** `body` will be removed. Follow the guide at https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/ to find a suitable replacement.
        /// **Reason:** The Team Discussions feature is deprecated in favor of Organization Discussions.
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// If true, restricts the visibility of this discussion to team members and organization owners. If false or not specified, allows any organization member to view this discussion.
        /// **Upcoming Change on 2024-07-01 UTC**
        /// **Description:** `private` will be removed. Follow the guide at https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/ to find a suitable replacement.
        /// **Reason:** The Team Discussions feature is deprecated in favor of Organization Discussions.
        /// </summary>
        public bool? Private { get; set; }
    }
}