namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateCheckSuite
    /// </summary>
    public class CreateCheckSuitePayload : QueryableValue<CreateCheckSuitePayload>
    {
        internal CreateCheckSuitePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// The newly created check suite.
        /// </summary>
        public CheckSuite CheckSuite => this.CreateProperty(x => x.CheckSuite, Octokit.GraphQL.Model.CheckSuite.Create);

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        internal static CreateCheckSuitePayload Create(Expression expression)
        {
            return new CreateCheckSuitePayload(expression);
        }
    }
}