namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of CreateUserList
    /// </summary>
    public class CreateUserListPayload : QueryableValue<CreateUserListPayload>
    {
        internal CreateUserListPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The list that was just created
        /// </summary>
        public UserList List => this.CreateProperty(x => x.List, Octokit.GraphQL.Model.UserList.Create);

        /// <summary>
        /// The user who created the list
        /// </summary>
        public User Viewer => this.CreateProperty(x => x.Viewer, Octokit.GraphQL.Model.User.Create);

        internal static CreateUserListPayload Create(Expression expression)
        {
            return new CreateUserListPayload(expression);
        }
    }
}