namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteIpAllowListEntry
    /// </summary>
    public class DeleteIpAllowListEntryPayload : QueryableValue<DeleteIpAllowListEntryPayload>
    {
        internal DeleteIpAllowListEntryPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The IP allow list entry that was deleted.
        /// </summary>
        public IpAllowListEntry IpAllowListEntry => this.CreateProperty(x => x.IpAllowListEntry, Octokit.GraphQL.Model.IpAllowListEntry.Create);

        internal static DeleteIpAllowListEntryPayload Create(Expression expression)
        {
            return new DeleteIpAllowListEntryPayload(expression);
        }
    }
}