namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of DeleteProjectV2Field
    /// </summary>
    public class DeleteProjectV2FieldInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the field to delete.
        /// </summary>
        public ID FieldId { get; set; }
    }
}