namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeletePullRequestReview
    /// </summary>
    public class DeletePullRequestReviewPayload : QueryableValue<DeletePullRequestReviewPayload>
    {
        internal DeletePullRequestReviewPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The deleted pull request review.
        /// </summary>
        public PullRequestReview PullRequestReview => this.CreateProperty(x => x.PullRequestReview, Octokit.GraphQL.Model.PullRequestReview.Create);

        internal static DeletePullRequestReviewPayload Create(Expression expression)
        {
            return new DeletePullRequestReviewPayload(expression);
        }
    }
}