namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteProjectV2Workflow
    /// </summary>
    public class DeleteProjectV2WorkflowPayload : QueryableValue<DeleteProjectV2WorkflowPayload>
    {
        internal DeleteProjectV2WorkflowPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The ID of the deleted workflow.
        /// </summary>
        public ID? DeletedWorkflowId { get; }

        /// <summary>
        /// The project the deleted workflow was in.
        /// </summary>
        public ProjectV2 ProjectV2 => this.CreateProperty(x => x.ProjectV2, Octokit.GraphQL.Model.ProjectV2.Create);

        internal static DeleteProjectV2WorkflowPayload Create(Expression expression)
        {
            return new DeleteProjectV2WorkflowPayload(expression);
        }
    }
}