namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeletePullRequestReviewComment
    /// </summary>
    public class DeletePullRequestReviewCommentPayload : QueryableValue<DeletePullRequestReviewCommentPayload>
    {
        internal DeletePullRequestReviewCommentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The pull request review the deleted comment belonged to.
        /// </summary>
        public PullRequestReview PullRequestReview => this.CreateProperty(x => x.PullRequestReview, Octokit.GraphQL.Model.PullRequestReview.Create);

        /// <summary>
        /// The deleted pull request review comment.
        /// </summary>
        public PullRequestReviewComment PullRequestReviewComment => this.CreateProperty(x => x.PullRequestReviewComment, Octokit.GraphQL.Model.PullRequestReviewComment.Create);

        internal static DeletePullRequestReviewCommentPayload Create(Expression expression)
        {
            return new DeletePullRequestReviewCommentPayload(expression);
        }
    }
}