namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of DeleteProject
    /// </summary>
    public class DeleteProjectPayload : QueryableValue<DeleteProjectPayload>
    {
        internal DeleteProjectPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The repository or organization the project was removed from.
        /// </summary>
        public IProjectOwner Owner => this.CreateProperty(x => x.Owner, Octokit.GraphQL.Model.Internal.StubIProjectOwner.Create);

        internal static DeleteProjectPayload Create(Expression expression)
        {
            return new DeleteProjectPayload(expression);
        }
    }
}