namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of EnqueuePullRequest
    /// </summary>
    public class EnqueuePullRequestInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the pull request to enqueue.
        /// </summary>
        public ID PullRequestId { get; set; }

        /// <summary>
        /// Add the pull request to the front of the queue.
        /// </summary>
        public bool? Jump { get; set; }

        /// <summary>
        /// The expected head OID of the pull request.
        /// </summary>
        public string ExpectedHeadOid { get; set; }
    }
}