namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of FollowOrganization
    /// </summary>
    public class FollowOrganizationPayload : QueryableValue<FollowOrganizationPayload>
    {
        internal FollowOrganizationPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The organization that was followed.
        /// </summary>
        public Organization Organization => this.CreateProperty(x => x.Organization, Octokit.GraphQL.Model.Organization.Create);

        internal static FollowOrganizationPayload Create(Expression expression)
        {
            return new FollowOrganizationPayload(expression);
        }
    }
}