namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of LinkProjectV2ToTeam
    /// </summary>
    public class LinkProjectV2ToTeamInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the project to link to the team.
        /// </summary>
        public ID ProjectId { get; set; }

        /// <summary>
        /// The ID of the team to link to the project.
        /// </summary>
        public ID TeamId { get; set; }
    }
}