namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of LinkProjectV2ToRepository
    /// </summary>
    public class LinkProjectV2ToRepositoryInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the project to link to the repository.
        /// </summary>
        public ID ProjectId { get; set; }

        /// <summary>
        /// The ID of the repository to link to the project.
        /// </summary>
        public ID RepositoryId { get; set; }
    }
}