namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of LockLockable
    /// </summary>
    public class LockLockableInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// ID of the item to be locked.
        /// </summary>
        public ID LockableId { get; set; }

        /// <summary>
        /// A reason for why the item will be locked.
        /// </summary>
        public LockReason? LockReason { get; set; }
    }
}