namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of MarkNotificationAsDone
    /// </summary>
    public class MarkNotificationAsDoneInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The NotificationThread id.
        /// </summary>
        public ID Id { get; set; }
    }
}