namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of MarkProjectV2AsTemplate
    /// </summary>
    public class MarkProjectV2AsTemplatePayload : QueryableValue<MarkProjectV2AsTemplatePayload>
    {
        internal MarkProjectV2AsTemplatePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The project.
        /// </summary>
        public ProjectV2 ProjectV2 => this.CreateProperty(x => x.ProjectV2, Octokit.GraphQL.Model.ProjectV2.Create);

        internal static MarkProjectV2AsTemplatePayload Create(Expression expression)
        {
            return new MarkProjectV2AsTemplatePayload(expression);
        }
    }
}