namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of MergePullRequest
    /// </summary>
    public class MergePullRequestInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// ID of the pull request to be merged.
        /// </summary>
        public ID PullRequestId { get; set; }

        /// <summary>
        /// Commit headline to use for the merge commit; if omitted, a default message will be used.
        /// </summary>
        public string CommitHeadline { get; set; }

        /// <summary>
        /// Commit body to use for the merge commit; if omitted, a default message will be used
        /// </summary>
        public string CommitBody { get; set; }

        /// <summary>
        /// OID that the pull request head ref must match to allow merge; if omitted, no check is performed.
        /// </summary>
        public string ExpectedHeadOid { get; set; }

        /// <summary>
        /// The merge method to use. If omitted, defaults to 'MERGE'
        /// </summary>
        public PullRequestMergeMethod? MergeMethod { get; set; }

        /// <summary>
        /// The email address to associate with this merge.
        /// </summary>
        public string AuthorEmail { get; set; }
    }
}