namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of MinimizeComment
    /// </summary>
    public class MinimizeCommentInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the subject to modify.
        /// </summary>
        public ID SubjectId { get; set; }

        /// <summary>
        /// The classification of comment
        /// </summary>
        public ReportedContentClassifiers Classifier { get; set; }
    }
}