namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RejectDeployments
    /// </summary>
    public class RejectDeploymentsPayload : QueryableValue<RejectDeploymentsPayload>
    {
        internal RejectDeploymentsPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The affected deployments.
        /// </summary>
        public IQueryableList<Deployment> Deployments => this.CreateProperty(x => x.Deployments);

        internal static RejectDeploymentsPayload Create(Expression expression)
        {
            return new RejectDeploymentsPayload(expression);
        }
    }
}