namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveEnterpriseIdentityProvider
    /// </summary>
    public class RemoveEnterpriseIdentityProviderPayload : QueryableValue<RemoveEnterpriseIdentityProviderPayload>
    {
        internal RemoveEnterpriseIdentityProviderPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The identity provider that was removed from the enterprise.
        /// </summary>
        public EnterpriseIdentityProvider IdentityProvider => this.CreateProperty(x => x.IdentityProvider, Octokit.GraphQL.Model.EnterpriseIdentityProvider.Create);

        internal static RemoveEnterpriseIdentityProviderPayload Create(Expression expression)
        {
            return new RemoveEnterpriseIdentityProviderPayload(expression);
        }
    }
}