namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveOutsideCollaborator
    /// </summary>
    public class RemoveOutsideCollaboratorPayload : QueryableValue<RemoveOutsideCollaboratorPayload>
    {
        internal RemoveOutsideCollaboratorPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The user that was removed as an outside collaborator.
        /// </summary>
        public User RemovedUser => this.CreateProperty(x => x.RemovedUser, Octokit.GraphQL.Model.User.Create);

        internal static RemoveOutsideCollaboratorPayload Create(Expression expression)
        {
            return new RemoveOutsideCollaboratorPayload(expression);
        }
    }
}