namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveEnterpriseSupportEntitlement
    /// </summary>
    public class RemoveEnterpriseSupportEntitlementPayload : QueryableValue<RemoveEnterpriseSupportEntitlementPayload>
    {
        internal RemoveEnterpriseSupportEntitlementPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// A message confirming the result of removing the support entitlement.
        /// </summary>
        public string Message { get; }

        internal static RemoveEnterpriseSupportEntitlementPayload Create(Expression expression)
        {
            return new RemoveEnterpriseSupportEntitlementPayload(expression);
        }
    }
}