namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveAssigneesFromAssignable
    /// </summary>
    public class RemoveAssigneesFromAssignablePayload : QueryableValue<RemoveAssigneesFromAssignablePayload>
    {
        internal RemoveAssigneesFromAssignablePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// The item that was unassigned.
        /// </summary>
        public IAssignable Assignable => this.CreateProperty(x => x.Assignable, Octokit.GraphQL.Model.Internal.StubIAssignable.Create);

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        internal static RemoveAssigneesFromAssignablePayload Create(Expression expression)
        {
            return new RemoveAssigneesFromAssignablePayload(expression);
        }
    }
}