namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveEnterpriseAdmin
    /// </summary>
    public class RemoveEnterpriseAdminPayload : QueryableValue<RemoveEnterpriseAdminPayload>
    {
        internal RemoveEnterpriseAdminPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// The user who was removed as an administrator.
        /// </summary>
        public User Admin => this.CreateProperty(x => x.Admin, Octokit.GraphQL.Model.User.Create);

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated enterprise.
        /// </summary>
        public Enterprise Enterprise => this.CreateProperty(x => x.Enterprise, Octokit.GraphQL.Model.Enterprise.Create);

        /// <summary>
        /// A message confirming the result of removing an administrator.
        /// </summary>
        public string Message { get; }

        /// <summary>
        /// The viewer performing the mutation.
        /// </summary>
        public User Viewer => this.CreateProperty(x => x.Viewer, Octokit.GraphQL.Model.User.Create);

        internal static RemoveEnterpriseAdminPayload Create(Expression expression)
        {
            return new RemoveEnterpriseAdminPayload(expression);
        }
    }
}