namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of RemoveLabelsFromLabelable
    /// </summary>
    public class RemoveLabelsFromLabelablePayload : QueryableValue<RemoveLabelsFromLabelablePayload>
    {
        internal RemoveLabelsFromLabelablePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The Labelable the labels were removed from.
        /// </summary>
        public ILabelable Labelable => this.CreateProperty(x => x.Labelable, Octokit.GraphQL.Model.Internal.StubILabelable.Create);

        internal static RemoveLabelsFromLabelablePayload Create(Expression expression)
        {
            return new RemoveLabelsFromLabelablePayload(expression);
        }
    }
}