namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of ReopenIssue
    /// </summary>
    public class ReopenIssuePayload : QueryableValue<ReopenIssuePayload>
    {
        internal ReopenIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The issue that was opened.
        /// </summary>
        public Issue Issue => this.CreateProperty(x => x.Issue, Octokit.GraphQL.Model.Issue.Create);

        internal static ReopenIssuePayload Create(Expression expression)
        {
            return new ReopenIssuePayload(expression);
        }
    }
}