namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of SubmitPullRequestReview
    /// </summary>
    public class SubmitPullRequestReviewPayload : QueryableValue<SubmitPullRequestReviewPayload>
    {
        internal SubmitPullRequestReviewPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The submitted pull request review.
        /// </summary>
        public PullRequestReview PullRequestReview => this.CreateProperty(x => x.PullRequestReview, Octokit.GraphQL.Model.PullRequestReview.Create);

        internal static SubmitPullRequestReviewPayload Create(Expression expression)
        {
            return new SubmitPullRequestReviewPayload(expression);
        }
    }
}