namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of TransferIssue
    /// </summary>
    public class TransferIssuePayload : QueryableValue<TransferIssuePayload>
    {
        internal TransferIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The issue that was transferred
        /// </summary>
        public Issue Issue => this.CreateProperty(x => x.Issue, Octokit.GraphQL.Model.Issue.Create);

        internal static TransferIssuePayload Create(Expression expression)
        {
            return new TransferIssuePayload(expression);
        }
    }
}