namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnfollowOrganization
    /// </summary>
    public class UnfollowOrganizationInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// ID of the organization to unfollow.
        /// </summary>
        public ID OrganizationId { get; set; }
    }
}