namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UnfollowOrganization
    /// </summary>
    public class UnfollowOrganizationPayload : QueryableValue<UnfollowOrganizationPayload>
    {
        internal UnfollowOrganizationPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The organization that was unfollowed.
        /// </summary>
        public Organization Organization => this.CreateProperty(x => x.Organization, Octokit.GraphQL.Model.Organization.Create);

        internal static UnfollowOrganizationPayload Create(Expression expression)
        {
            return new UnfollowOrganizationPayload(expression);
        }
    }
}