namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UnlinkProjectV2FromTeam
    /// </summary>
    public class UnlinkProjectV2FromTeamPayload : QueryableValue<UnlinkProjectV2FromTeamPayload>
    {
        internal UnlinkProjectV2FromTeamPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The team the project is unlinked from
        /// </summary>
        public Team Team => this.CreateProperty(x => x.Team, Octokit.GraphQL.Model.Team.Create);

        internal static UnlinkProjectV2FromTeamPayload Create(Expression expression)
        {
            return new UnlinkProjectV2FromTeamPayload(expression);
        }
    }
}