namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnmarkIssueAsDuplicate
    /// </summary>
    public class UnmarkIssueAsDuplicateInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// ID of the issue or pull request currently marked as a duplicate.
        /// </summary>
        public ID DuplicateId { get; set; }

        /// <summary>
        /// ID of the issue or pull request currently considered canonical/authoritative/original.
        /// </summary>
        public ID CanonicalId { get; set; }
    }
}