namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UnmarkDiscussionCommentAsAnswer
    /// </summary>
    public class UnmarkDiscussionCommentAsAnswerInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the discussion comment to unmark as an answer.
        /// </summary>
        public ID Id { get; set; }
    }
}