namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UnmarkIssueAsDuplicate
    /// </summary>
    public class UnmarkIssueAsDuplicatePayload : QueryableValue<UnmarkIssueAsDuplicatePayload>
    {
        internal UnmarkIssueAsDuplicatePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The issue or pull request that was marked as a duplicate.
        /// </summary>
        public IssueOrPullRequest Duplicate => this.CreateProperty(x => x.Duplicate, Octokit.GraphQL.Model.IssueOrPullRequest.Create);

        internal static UnmarkIssueAsDuplicatePayload Create(Expression expression)
        {
            return new UnmarkIssueAsDuplicatePayload(expression);
        }
    }
}