namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UnpinIssue
    /// </summary>
    public class UnpinIssuePayload : QueryableValue<UnpinIssuePayload>
    {
        internal UnpinIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The id of the pinned issue that was unpinned
        /// </summary>
        public ID? Id { get; }

        /// <summary>
        /// The issue that was unpinned
        /// </summary>
        public Issue Issue => this.CreateProperty(x => x.Issue, Octokit.GraphQL.Model.Issue.Create);

        internal static UnpinIssuePayload Create(Expression expression)
        {
            return new UnpinIssuePayload(expression);
        }
    }
}