namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateBranchProtectionRule
    /// </summary>
    public class UpdateBranchProtectionRulePayload : QueryableValue<UpdateBranchProtectionRulePayload>
    {
        internal UpdateBranchProtectionRulePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// The newly created BranchProtectionRule.
        /// </summary>
        public BranchProtectionRule BranchProtectionRule => this.CreateProperty(x => x.BranchProtectionRule, Octokit.GraphQL.Model.BranchProtectionRule.Create);

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        internal static UpdateBranchProtectionRulePayload Create(Expression expression)
        {
            return new UpdateBranchProtectionRulePayload(expression);
        }
    }
}