namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateProjectV2DraftIssue
    /// </summary>
    public class UpdateProjectV2DraftIssuePayload : QueryableValue<UpdateProjectV2DraftIssuePayload>
    {
        internal UpdateProjectV2DraftIssuePayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The draft issue updated in the project.
        /// </summary>
        public DraftIssue DraftIssue => this.CreateProperty(x => x.DraftIssue, Octokit.GraphQL.Model.DraftIssue.Create);

        internal static UpdateProjectV2DraftIssuePayload Create(Expression expression)
        {
            return new UpdateProjectV2DraftIssuePayload(expression);
        }
    }
}