namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateIpAllowListEnabledSetting
    /// </summary>
    public class UpdateIpAllowListEnabledSettingInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the owner on which to set the IP allow list enabled setting.
        /// </summary>
        public ID OwnerId { get; set; }

        /// <summary>
        /// The value for the IP allow list enabled setting.
        /// </summary>
        public IpAllowListEnabledSettingValue SettingValue { get; set; }
    }
}