namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateEnvironment
    /// </summary>
    public class UpdateEnvironmentPayload : QueryableValue<UpdateEnvironmentPayload>
    {
        internal UpdateEnvironmentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated environment.
        /// </summary>
        public Environment Environment => this.CreateProperty(x => x.Environment, Octokit.GraphQL.Model.Environment.Create);

        internal static UpdateEnvironmentPayload Create(Expression expression)
        {
            return new UpdateEnvironmentPayload(expression);
        }
    }
}