namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateDiscussion
    /// </summary>
    public class UpdateDiscussionPayload : QueryableValue<UpdateDiscussionPayload>
    {
        internal UpdateDiscussionPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The modified discussion.
        /// </summary>
        public Discussion Discussion => this.CreateProperty(x => x.Discussion, Octokit.GraphQL.Model.Discussion.Create);

        internal static UpdateDiscussionPayload Create(Expression expression)
        {
            return new UpdateDiscussionPayload(expression);
        }
    }
}