namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateIpAllowListEntry
    /// </summary>
    public class UpdateIpAllowListEntryPayload : QueryableValue<UpdateIpAllowListEntryPayload>
    {
        internal UpdateIpAllowListEntryPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The IP allow list entry that was updated.
        /// </summary>
        public IpAllowListEntry IpAllowListEntry => this.CreateProperty(x => x.IpAllowListEntry, Octokit.GraphQL.Model.IpAllowListEntry.Create);

        internal static UpdateIpAllowListEntryPayload Create(Expression expression)
        {
            return new UpdateIpAllowListEntryPayload(expression);
        }
    }
}