namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateEnterpriseMembersCanMakePurchasesSetting
    /// </summary>
    public class UpdateEnterpriseMembersCanMakePurchasesSettingInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ID of the enterprise on which to set the members can make purchases setting.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// The value for the members can make purchases setting on the enterprise.
        /// </summary>
        public EnterpriseMembersCanMakePurchasesSettingValue SettingValue { get; set; }
    }
}