namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateTeamsRepository
    /// </summary>
    public class UpdateTeamsRepositoryPayload : QueryableValue<UpdateTeamsRepositoryPayload>
    {
        internal UpdateTeamsRepositoryPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The repository that was updated.
        /// </summary>
        public Repository Repository => this.CreateProperty(x => x.Repository, Octokit.GraphQL.Model.Repository.Create);

        /// <summary>
        /// The teams granted permission on the repository.
        /// </summary>
        public IQueryableList<Team> Teams => this.CreateProperty(x => x.Teams);

        internal static UpdateTeamsRepositoryPayload Create(Expression expression)
        {
            return new UpdateTeamsRepositoryPayload(expression);
        }
    }
}