namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateEnterpriseProfile
    /// </summary>
    public class UpdateEnterpriseProfileInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Enterprise ID to update.
        /// </summary>
        public ID EnterpriseId { get; set; }

        /// <summary>
        /// The name of the enterprise.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The description of the enterprise.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The URL of the enterprise's website.
        /// </summary>
        public string WebsiteUrl { get; set; }

        /// <summary>
        /// The location of the enterprise.
        /// </summary>
        public string Location { get; set; }
    }
}