namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateEnterpriseMembersCanViewDependencyInsightsSetting
    /// </summary>
    public class UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload : QueryableValue<UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload>
    {
        internal UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The enterprise with the updated members can view dependency insights setting.
        /// </summary>
        public Enterprise Enterprise => this.CreateProperty(x => x.Enterprise, Octokit.GraphQL.Model.Enterprise.Create);

        /// <summary>
        /// A message confirming the result of updating the members can view dependency insights setting.
        /// </summary>
        public string Message { get; }

        internal static UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload Create(Expression expression)
        {
            return new UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload(expression);
        }
    }
}