namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateTeamDiscussionComment
    /// </summary>
    public class UpdateTeamDiscussionCommentPayload : QueryableValue<UpdateTeamDiscussionCommentPayload>
    {
        internal UpdateTeamDiscussionCommentPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated comment.
        /// </summary>
        public TeamDiscussionComment TeamDiscussionComment => this.CreateProperty(x => x.TeamDiscussionComment, Octokit.GraphQL.Model.TeamDiscussionComment.Create);

        internal static UpdateTeamDiscussionCommentPayload Create(Expression expression)
        {
            return new UpdateTeamDiscussionCommentPayload(expression);
        }
    }
}