namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateEnterpriseMembersCanDeleteRepositoriesSetting
    /// </summary>
    public class UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload : QueryableValue<UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload>
    {
        internal UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The enterprise with the updated members can delete repositories setting.
        /// </summary>
        public Enterprise Enterprise => this.CreateProperty(x => x.Enterprise, Octokit.GraphQL.Model.Enterprise.Create);

        /// <summary>
        /// A message confirming the result of updating the members can delete repositories setting.
        /// </summary>
        public string Message { get; }

        internal static UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload Create(Expression expression)
        {
            return new UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload(expression);
        }
    }
}