namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateUserListsForItem
    /// </summary>
    public class UpdateUserListsForItemPayload : QueryableValue<UpdateUserListsForItemPayload>
    {
        internal UpdateUserListsForItemPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The item that was added
        /// </summary>
        public UserListItems Item => this.CreateProperty(x => x.Item, Octokit.GraphQL.Model.UserListItems.Create);

        /// <summary>
        /// The lists to which this item belongs
        /// </summary>
        public IQueryableList<UserList> Lists => this.CreateProperty(x => x.Lists);

        /// <summary>
        /// The user who owns the lists
        /// </summary>
        public User User => this.CreateProperty(x => x.User, Octokit.GraphQL.Model.User.Create);

        internal static UpdateUserListsForItemPayload Create(Expression expression)
        {
            return new UpdateUserListsForItemPayload(expression);
        }
    }
}