namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateEnterpriseDefaultRepositoryPermissionSetting
    /// </summary>
    public class UpdateEnterpriseDefaultRepositoryPermissionSettingPayload : QueryableValue<UpdateEnterpriseDefaultRepositoryPermissionSettingPayload>
    {
        internal UpdateEnterpriseDefaultRepositoryPermissionSettingPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The enterprise with the updated base repository permission setting.
        /// </summary>
        public Enterprise Enterprise => this.CreateProperty(x => x.Enterprise, Octokit.GraphQL.Model.Enterprise.Create);

        /// <summary>
        /// A message confirming the result of updating the base repository permission setting.
        /// </summary>
        public string Message { get; }

        internal static UpdateEnterpriseDefaultRepositoryPermissionSettingPayload Create(Expression expression)
        {
            return new UpdateEnterpriseDefaultRepositoryPermissionSettingPayload(expression);
        }
    }
}