namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateOrganizationWebCommitSignoffSetting
    /// </summary>
    public class UpdateOrganizationWebCommitSignoffSettingPayload : QueryableValue<UpdateOrganizationWebCommitSignoffSettingPayload>
    {
        internal UpdateOrganizationWebCommitSignoffSettingPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// A message confirming the result of updating the web commit signoff setting.
        /// </summary>
        public string Message { get; }

        /// <summary>
        /// The organization with the updated web commit signoff setting.
        /// </summary>
        public Organization Organization => this.CreateProperty(x => x.Organization, Octokit.GraphQL.Model.Organization.Create);

        internal static UpdateOrganizationWebCommitSignoffSettingPayload Create(Expression expression)
        {
            return new UpdateOrganizationWebCommitSignoffSettingPayload(expression);
        }
    }
}