namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using Octokit.GraphQL.Core;
    using Octokit.GraphQL.Core.Builders;

    /// <summary>
    /// Autogenerated return type of UpdateProjectColumn
    /// </summary>
    public class UpdateProjectColumnPayload : QueryableValue<UpdateProjectColumnPayload>
    {
        internal UpdateProjectColumnPayload(Expression expression) : base(expression)
        {
        }

        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; }

        /// <summary>
        /// The updated project column.
        /// </summary>
        public ProjectColumn ProjectColumn => this.CreateProperty(x => x.ProjectColumn, Octokit.GraphQL.Model.ProjectColumn.Create);

        internal static UpdateProjectColumnPayload Create(Expression expression)
        {
            return new UpdateProjectColumnPayload(expression);
        }
    }
}