namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateProjectColumn
    /// </summary>
    public class UpdateProjectColumnInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The ProjectColumn ID to update.
        /// </summary>
        public ID ProjectColumnId { get; set; }

        /// <summary>
        /// The name of project column.
        /// </summary>
        public string Name { get; set; }
    }
}