namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateEnvironment
    /// </summary>
    public class UpdateEnvironmentInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The node ID of the environment.
        /// </summary>
        public ID EnvironmentId { get; set; }

        /// <summary>
        /// The wait timer in minutes.
        /// </summary>
        public int? WaitTimer { get; set; }

        /// <summary>
        /// The ids of users or teams that can approve deployments to this environment
        /// </summary>
        public IEnumerable<ID> Reviewers { get; set; }

        /// <summary>
        /// Whether deployments to this environment can be approved by the user who created the deployment.
        /// </summary>
        public bool? PreventSelfReview { get; set; }
    }
}