namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateDiscussion
    /// </summary>
    public class UpdateDiscussionInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The Node ID of the discussion to update.
        /// </summary>
        public ID DiscussionId { get; set; }

        /// <summary>
        /// The new discussion title.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The new contents of the discussion body.
        /// </summary>
        public string Body { get; set; }

        /// <summary>
        /// The Node ID of a discussion category within the same repository to change this discussion to.
        /// </summary>
        public ID? CategoryId { get; set; }
    }
}