namespace Octokit.GraphQL.Model
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Autogenerated input type of UpdateUserListsForItem
    /// </summary>
    public class UpdateUserListsForItemInput
    {
        /// <summary>
        /// A unique identifier for the client performing the mutation.
        /// </summary>
        public string ClientMutationId { get; set; }

        /// <summary>
        /// The item to add to the list
        /// </summary>
        public ID ItemId { get; set; }

        /// <summary>
        /// The lists to which this item should belong
        /// </summary>
        public IEnumerable<ID> ListIds { get; set; }

        /// <summary>
        /// The suggested lists to create and add this item to
        /// </summary>
        public IEnumerable<ID> SuggestedListIds { get; set; }
    }
}