name: 🐛 Bug Report
description: Create a bug report to help us improve FluentHub!
labels: [bug]
assignees: [0x5bfa]
title: "Bug: "
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Assets
      description: |
        A list of assets (errors, screenshots) relevant to the bug.
  - type: textarea
    attributes:
      label: FluentHub version
      description: Copy and paste the version from the about page of FluentHub's settings. If you're building from GitHub, simply provide the commit hash you built on.
    validations:
      required: true
  - type: dropdown
    id: windows
    attributes:
      label: Windows version
      multiple: true
      options:
        - "Windows Insider Build (xxxxx)"
        - "Windows 11 (26H1): Build 28000"
        - "Windows 11 (25H2): Build 26200"
        - "Windows 11 (24H2): Build 26120"
        - "Windows 11 (24H2): Build 26100"
        - "Windows 11 (23H2): Build 22631"
        - "Windows 11 (22H2): Build 22621"
        - "Windows 11 (21H2): Build 22000"
        - "Windows 10 (21H2): Build 19044"
        - "Windows 10 (21H1): Build 19043"
        - "Windows 10 (20H2): Build 19042"
        - "Windows 10 (1809): Build 17763"
    validations:
      required: true
