name: ➕ Feature Request
description: Request a new feature for FluentHub
labels: [feature request]
body:
  - type: checkboxes
    attributes:
      label: ⏱️ Before you start...
      options:
        - label: Have you checked if a similar feature request has already been reported?
          required: true
  - type: textarea
    attributes:
      label: 📄 Description
      description: A clear and concise description of what your idea is. Include things like possible use cases, drawbacks, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🗃️ Alternative solutions
      description: Describe more ways this idea could be implemented.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📸 Assets
      description: |
        A list of assets (screenshots, mockups) relevant to this feature request.
