name: 💬 Feature Discussion
description: Tracker for a feature
labels: [tracker]
body:
  - type: textarea
    attributes:
      label: 🛤️ Feature
      description: What feature is this related to?
    validations:
      required: false
  - type: textarea
    attributes:
      label: 📄 Description
      description: A clear and concise description of what your idea is. Include things like possible use cases, drawbacks, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📸 Assets
      description: A list of assets (screenshots, mockups) relevant to this feature request.
