using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.UI;
using Windows.UI.Xaml.Media;

namespace FluentHub.Helpers
{
    public class LanguageColorHelpers
    {
        public static SolidColorBrush Get(string language)
        {
            string hexColor = "000000";

            #region languages
            _ = language switch
            {
                "1C Enterprise" => hexColor = "814CCC",
                "4D" => hexColor = "004289",
                "ABAP" => hexColor = "E8274B",
                "ABAP CDS" => hexColor = "555e25",
                "ActionScript" => hexColor = "882B0F",
                "Ada" => hexColor = "02f88c",
                "Adobe Font Metrics" => hexColor = "fa0f00",
                "Agda" => hexColor = "315665",
                "AGS Script" => hexColor = "B9D9FF",
                "AIDL" => hexColor = "34EB6B",
                "AL" => hexColor = "3AA2B5",
                "Alloy" => hexColor = "64C800",
                "Alpine Abuild" => hexColor = "0D597F",
                "Altium Designer" => hexColor = "A89663",
                "AMPL" => hexColor = "E6EFBB",
                "AngelScript" => hexColor = "C7D7DC",
                "Ant Build System" => hexColor = "A9157E",
                "ANTLR" => hexColor = "9DC3FF",
                "ApacheConf" => hexColor = "d12127",
                "Apex" => hexColor = "1797c0",
                "API Blueprint" => hexColor = "2ACCA8",
                "APL" => hexColor = "5A8164",
                "Apollo Guidance Computer" => hexColor = "0B3D91",
                "AppleScript" => hexColor = "101F1F",
                "Arc" => hexColor = "aa2afe",
                "AsciiDoc" => hexColor = "73a0c5",
                "ASP.NET" => hexColor = "9400ff",
                "AspectJ" => hexColor = "a957b0",
                "Assembly" => hexColor = "6E4C13",
                "Astro" => hexColor = "ff5a03",
                "Asymptote" => hexColor = "ff0000",
                "ATS" => hexColor = "1ac620",
                "Augeas" => hexColor = "9CC134",
                "AutoHotkey" => hexColor = "6594b9",
                "AutoIt" => hexColor = "1C3552",
                "Avro IDL" => hexColor = "0040FF",
                "Awk" => hexColor = "c30e9b",
                "Ballerina" => hexColor = "FF5000",
                "BASIC" => hexColor = "ff0000",
                "Batchfile" => hexColor = "C1F12E",
                "Beef" => hexColor = "a52f4e",
                "BibTeX" => hexColor = "778899",
                "Bicep" => hexColor = "519aba",
                "Bison" => hexColor = "6A463F",
                "BitBake" => hexColor = "00bce4",
                "Blade" => hexColor = "f7523f",
                "BlitzBasic" => hexColor = "00FFAE",
                "BlitzMax" => hexColor = "cd6400",
                "Bluespec" => hexColor = "12223c",
                "Boo" => hexColor = "d4bec1",
                "Boogie" => hexColor = "c80fa0",
                "Brainfuck" => hexColor = "2F2530",
                "Brightscript" => hexColor = "662D91",
                "Browserslist" => hexColor = "ffd539",
                "C" => hexColor = "555555",
                "C#" => hexColor = "178600",
                "C++" => hexColor = "f34b7d",
                "Cabal Config" => hexColor = "483465",
                "Cap'n Proto" => hexColor = "c42727",
                "Ceylon" => hexColor = "dfa535",
                "Chapel" => hexColor = "8dc63f",
                "ChucK" => hexColor = "3f8000",
                "Cirru" => hexColor = "ccccff",
                "Clarion" => hexColor = "db901e",
                "Classic ASP" => hexColor = "6a40fd",
                "Clean" => hexColor = "3F85AF",
                "Click" => hexColor = "E4E6F3",
                "CLIPS" => hexColor = "00A300",
                "Clojure" => hexColor = "db5855",
                "Closure Templates" => hexColor = "0d948f",
                "Cloud Firestore Security Rules" => hexColor = "FFA000",
                "CMake" => hexColor = "DA3434",
                "CodeQL" => hexColor = "140f46",
                "CoffeeScript" => hexColor = "244776",
                "ColdFusion" => hexColor = "ed2cd6",
                "ColdFusion CFC" => hexColor = "ed2cd6",
                "COLLADA" => hexColor = "F1A42B",
                "Common Lisp" => hexColor = "3fb68b",
                "Common Workflow Language" => hexColor = "B5314C",
                "Component Pascal" => hexColor = "B0CE4E",
                "Coq" => hexColor = "d0b68c",
                "Crystal" => hexColor = "000100",
                "CSON" => hexColor = "244776",
                "Csound" => hexColor = "1a1a1a",
                "Csound Document" => hexColor = "1a1a1a",
                "Csound Score" => hexColor = "1a1a1a",
                "CSS" => hexColor = "563d7c",
                "CSV" => hexColor = "237346",
                "Cuda" => hexColor = "3A4E3A",
                "CUE" => hexColor = "5886E1",
                "CWeb" => hexColor = "00007a",
                "Cython" => hexColor = "fedf5b",
                "D" => hexColor = "ba595e",
                "Dafny" => hexColor = "FFEC25",
                "Darcs Patch" => hexColor = "8eff23",
                "Dart" => hexColor = "00B4AB",
                "DataWeave" => hexColor = "003a52",
                "Dhall" => hexColor = "dfafff",
                "DirectX 3D File" => hexColor = "aace60",
                "DM" => hexColor = "447265",
                "Dockerfile" => hexColor = "384d54",
                "Dogescript" => hexColor = "cca760",
                "Dylan" => hexColor = "6c616e",
                "E" => hexColor = "ccce35",
                "Earthly" => hexColor = "2af0ff",
                "Easybuild" => hexColor = "069406",
                "eC" => hexColor = "913960",
                "Ecere Projects" => hexColor = "913960",
                "ECL" => hexColor = "8a1267",
                "ECLiPSe" => hexColor = "001d9d",
                "EditorConfig" => hexColor = "fff1f2",
                "Eiffel" => hexColor = "4d6977",
                "EJS" => hexColor = "a91e50",
                "Elixir" => hexColor = "6e4a7e",
                "Elm" => hexColor = "60B5CC",
                "Emacs Lisp" => hexColor = "c065db",
                "EmberScript" => hexColor = "FFF4F3",
                "EQ" => hexColor = "a78649",
                "Erlang" => hexColor = "B83998",
                "F#" => hexColor = "b845fc",
                "F*" => hexColor = "572e30",
                "Factor" => hexColor = "636746",
                "Fancy" => hexColor = "7b9db4",
                "Fantom" => hexColor = "14253c",
                "Faust" => hexColor = "c37240",
                "Fennel" => hexColor = "fff3d7",
                "FIGlet Font" => hexColor = "FFDDBB",
                "Filebench WML" => hexColor = "F6B900",
                "fish" => hexColor = "4aae47",
                "Fluent" => hexColor = "ffcc33",
                "FLUX" => hexColor = "88ccff",
                "Forth" => hexColor = "341708",
                "Fortran" => hexColor = "4d41b1",
                "Fortran Free Form" => hexColor = "4d41b1",
                "FreeBasic" => hexColor = "867db1",
                "FreeMarker" => hexColor = "0050b2",
                "Frege" => hexColor = "00cafe",
                "Futhark" => hexColor = "5f021f",
                "G-code" => hexColor = "D08CF2",
                "Game Maker Language" => hexColor = "71b417",
                "GAML" => hexColor = "FFC766",
                "GAMS" => hexColor = "f49a22",
                "GAP" => hexColor = "0000cc",
                "GCC Machine Description" => hexColor = "FFCFAB",
                "GDScript" => hexColor = "355570",
                "GEDCOM" => hexColor = "003058",
                "Gemfile.lock" => hexColor = "701516",
                "Genie" => hexColor = "fb855d",
                "Genshi" => hexColor = "951531",
                "Gentoo Ebuild" => hexColor = "9400ff",
                "Gentoo Eclass" => hexColor = "9400ff",
                "Gerber Image" => hexColor = "d20b00",
                "Gherkin" => hexColor = "5B2063",
                "Git Attributes" => hexColor = "F44D27",
                "Git Config" => hexColor = "F44D27",
                "GLSL" => hexColor = "5686a5",
                "Glyph" => hexColor = "c1ac7f",
                "Gnuplot" => hexColor = "f0a9f0",
                "Go" => hexColor = "00ADD8",
                "Go Checksums" => hexColor = "00ADD8",
                "Go Module" => hexColor = "00ADD8",
                "Golo" => hexColor = "88562A",
                "Gosu" => hexColor = "82937f",
                "Grace" => hexColor = "615f8b",
                "Gradle" => hexColor = "02303a",
                "Grammatical Framework" => hexColor = "ff0000",
                "GraphQL" => hexColor = "e10098",
                "Graphviz (DOT)" => hexColor = "2596be",
                "Groovy" => hexColor = "4298b8",
                "Groovy Server Pages" => hexColor = "4298b8",
                "Hack" => hexColor = "878787",
                "Haml" => hexColor = "ece2a9",
                "Handlebars" => hexColor = "f7931e",
                "HAProxy" => hexColor = "106da9",
                "Harbour" => hexColor = "0e60e3",
                "Haskell" => hexColor = "5e5086",
                "Haxe" => hexColor = "df7900",
                "HiveQL" => hexColor = "dce200",
                "HLSL" => hexColor = "aace60",
                "HolyC" => hexColor = "ffefaf",
                "HTML" => hexColor = "e34c26",
                "HTML+ECR" => hexColor = "2e1052",
                "HTML+EEX" => hexColor = "6e4a7e",
                "HTML+ERB" => hexColor = "701516",
                "HTML+PHP" => hexColor = "4f5d95",
                "HTML+Razor" => hexColor = "512be4",
                "HTTP" => hexColor = "005C9C",
                "HXML" => hexColor = "f68712",
                "Hy" => hexColor = "7790B2",
                "IDL" => hexColor = "a3522f",
                "Idris" => hexColor = "b30000",
                "Ignore List" => hexColor = "000000",
                "IGOR Pro" => hexColor = "0000cc",
                "ImageJ Macro" => hexColor = "99AAFF",
                "INI" => hexColor = "d1dbe0",
                "Inno Setup" => hexColor = "264b99",
                "Io" => hexColor = "a9188d",
                "Ioke" => hexColor = "078193",
                "Isabelle" => hexColor = "FEFE00",
                "Isabelle ROOT" => hexColor = "FEFE00",
                "J" => hexColor = "9EEDFF",
                "JAR Manifest" => hexColor = "b07219",
                "Jasmin" => hexColor = "d03600",
                "Java" => hexColor = "b07219",
                "Java Properties" => hexColor = "2A6277",
                "Java Server Pages" => hexColor = "2A6277",
                "JavaScript" => hexColor = "f1e05a",
                "JavaScript+ERB" => hexColor = "f1e05a",
                "Jest Snapshot" => hexColor = "15c213",
                "JFlex" => hexColor = "DBCA00",
                "Jinja" => hexColor = "a52a22",
                "Jison" => hexColor = "56b3cb",
                "Jison Lex" => hexColor = "56b3cb",
                "Jolie" => hexColor = "843179",
                "jq" => hexColor = "c7254e",
                "JSON" => hexColor = "292929",
                "JSON with Comments" => hexColor = "292929",
                "JSON5" => hexColor = "267CB9",
                "JSONiq" => hexColor = "40d47e",
                "JSONLD" => hexColor = "0c479c",
                "Jsonnet" => hexColor = "0064bd",
                "Julia" => hexColor = "a270ba",
                "Jupyter Notebook" => hexColor = "DA5B0B",
                "Kaitai Struct" => hexColor = "773b37",
                "KakouneScript" => hexColor = "6f8042",
                "KiCad Layout" => hexColor = "2f4aab",
                "KiCad Legacy Layout" => hexColor = "2f4aab",
                "KiCad Schematic" => hexColor = "2f4aab",
                "Kotlin" => hexColor = "A97BFF",
                "KRL" => hexColor = "28430A",
                "LabVIEW" => hexColor = "fede06",
                "Lark" => hexColor = "2980B9",
                "Lasso" => hexColor = "999999",
                "Latte" => hexColor = "f2a542",
                "Less" => hexColor = "1d365d",
                "Lex" => hexColor = "DBCA00",
                "LFE" => hexColor = "4C3023",
                "LilyPond" => hexColor = "9ccc7c",
                "Liquid" => hexColor = "67b8de",
                "Literate Agda" => hexColor = "315665",
                "Literate CoffeeScript" => hexColor = "244776",
                "Literate Haskell" => hexColor = "5e5086",
                "LiveScript" => hexColor = "499886",
                "LLVM" => hexColor = "185619",
                "Logtalk" => hexColor = "295b9a",
                "LOLCODE" => hexColor = "cc9900",
                "LookML" => hexColor = "652B81",
                "LSL" => hexColor = "3d9970",
                "Lua" => hexColor = "000080",
                "Macaulay2" => hexColor = "d8ffff",
                "Makefile" => hexColor = "427819",
                "Mako" => hexColor = "7e858d",
                "Markdown" => hexColor = "083fa1",
                "Marko" => hexColor = "42bff2",
                "Mask" => hexColor = "f97732",
                "Mathematica" => hexColor = "dd1100",
                "MATLAB" => hexColor = "e16737",
                "Max" => hexColor = "c4a79c",
                "MAXScript" => hexColor = "00a6a6",
                "mcfunction" => hexColor = "E22837",
                "Mercury" => hexColor = "ff2b2b",
                "Meson" => hexColor = "007800",
                "Metal" => hexColor = "8f14e9",
                "Mirah" => hexColor = "c7a938",
                "mIRC Script" => hexColor = "3d57c3",
                "MLIR" => hexColor = "5EC8DB",
                "Modelica" => hexColor = "de1d31",
                "Modula-2" => hexColor = "10253f",
                "Modula-3" => hexColor = "223388",
                "MoonScript" => hexColor = "ff4585",
                "Motoko" => hexColor = "fbb03b",
                "Motorola 68K Assembly" => hexColor = "005daa",
                "MQL4" => hexColor = "62A8D6",
                "MQL5" => hexColor = "4A76B8",
                "MTML" => hexColor = "b7e1f4",
                "mupad" => hexColor = "244963",
                "Mustache" => hexColor = "724b3b",
                "nanorc" => hexColor = "2d004d",
                "NCL" => hexColor = "28431f",
                "Nearley" => hexColor = "990000",
                "Nemerle" => hexColor = "3d3c6e",
                "nesC" => hexColor = "94B0C7",
                "NetLinx" => hexColor = "0aa0ff",
                "NetLinx+ERB" => hexColor = "747faa",
                "NetLogo" => hexColor = "ff6375",
                "NewLisp" => hexColor = "87AED7",
                "Nextflow" => hexColor = "3ac486",
                "Nginx" => hexColor = "009639",
                "Nim" => hexColor = "ffc200",
                "Nit" => hexColor = "009917",
                "Nix" => hexColor = "7e7eff",
                "NPM Config" => hexColor = "cb3837",
                "Nu" => hexColor = "c9df40",
                "NumPy" => hexColor = "9C8AF9",
                "Nunjucks" => hexColor = "3d8137",
                "NWScript" => hexColor = "111522",
                "Objective-C" => hexColor = "438eff",
                "Objective-C++" => hexColor = "6866fb",
                "Objective-J" => hexColor = "ff0c5a",
                "ObjectScript" => hexColor = "424893",
                "OCaml" => hexColor = "3be133",
                "Odin" => hexColor = "60AFFE",
                "Omgrofl" => hexColor = "cabbff",
                "ooc" => hexColor = "b0b77e",
                "Opal" => hexColor = "f7ede0",
                "Open Policy Agent" => hexColor = "7d9199",
                "OpenCL" => hexColor = "ed2e2d",
                "OpenEdge ABL" => hexColor = "5ce600",
                "OpenQASM" => hexColor = "AA70FF",
                "OpenSCAD" => hexColor = "e5cd45",
                "Org" => hexColor = "77aa99",
                "Oxygene" => hexColor = "cdd0e3",
                "Oz" => hexColor = "fab738",
                "P4" => hexColor = "7055b5",
                "Pan" => hexColor = "cc0000",
                "Papyrus" => hexColor = "6600cc",
                "Parrot" => hexColor = "f3ca0a",
                "Pascal" => hexColor = "E3F171",
                "Pawn" => hexColor = "dbb284",
                "PEG.js" => hexColor = "234d6b",
                "Pep8" => hexColor = "C76F5B",
                "Perl" => hexColor = "0298c3",
                "PHP" => hexColor = "4F5D95",
                "PicoLisp" => hexColor = "6067af",
                "PigLatin" => hexColor = "fcd7de",
                "Pike" => hexColor = "005390",
                "PLpgSQL" => hexColor = "336790",
                "PLSQL" => hexColor = "dad8d8",
                "PogoScript" => hexColor = "d80074",
                "PostCSS" => hexColor = "dc3a0c",
                "PostScript" => hexColor = "da291c",
                "POV-Ray SDL" => hexColor = "6bac65",
                "PowerBuilder" => hexColor = "8f0f8d",
                "PowerShell" => hexColor = "012456",
                "Prisma" => hexColor = "0c344b",
                "Processing" => hexColor = "0096D8",
                "Prolog" => hexColor = "74283c",
                "Promela" => hexColor = "de0000",
                "Propeller Spin" => hexColor = "7fa2a7",
                "Pug" => hexColor = "a86454",
                "Puppet" => hexColor = "302B6D",
                "PureBasic" => hexColor = "5a6986",
                "PureScript" => hexColor = "1D222D",
                "Python" => hexColor = "3572A5",
                "Python console" => hexColor = "3572A5",
                "Python traceback" => hexColor = "3572A5",
                "q" => hexColor = "0040cd",
                "Q#" => hexColor = "fed659",
                "QML" => hexColor = "44a51c",
                "Qt Script" => hexColor = "00b841",
                "Quake" => hexColor = "882233",
                "R" => hexColor = "198CE7",
                "Racket" => hexColor = "3c5caa",
                "Ragel" => hexColor = "9d5200",
                "Raku" => hexColor = "0000fb",
                "RAML" => hexColor = "77d9fb",
                "Rascal" => hexColor = "fffaa0",
                "RDoc" => hexColor = "701516",
                "Reason" => hexColor = "ff5847",
                "Rebol" => hexColor = "358a5b",
                "Record Jar" => hexColor = "0673ba",
                "Red" => hexColor = "f50000",
                "Regular Expression" => hexColor = "009a00",
                "Ren'Py" => hexColor = "ff7f7f",
                "ReScript" => hexColor = "ed5051",
                "reStructuredText" => hexColor = "141414",
                "REXX" => hexColor = "d90e09",
                "Ring" => hexColor = "2D54CB",
                "Riot" => hexColor = "A71E49",
                "RMarkdown" => hexColor = "198ce7",
                "RobotFramework" => hexColor = "00c0b5",
                "Roff" => hexColor = "ecdebe",
                "Roff Manpage" => hexColor = "ecdebe",
                "Rouge" => hexColor = "cc0088",
                "Ruby" => hexColor = "701516",
                "RUNOFF" => hexColor = "665a4e",
                "Rust" => hexColor = "dea584",
                "SaltStack" => hexColor = "646464",
                "SAS" => hexColor = "B34936",
                "Sass" => hexColor = "a53b70",
                "Scala" => hexColor = "c22d40",
                "Scaml" => hexColor = "bd181a",
                "Scheme" => hexColor = "1e4aec",
                "Scilab" => hexColor = "ca0f21",
                "SCSS" => hexColor = "c6538c",
                "sed" => hexColor = "64b970",
                "Self" => hexColor = "0579aa",
                "ShaderLab" => hexColor = "222c37",
                "Shell" => hexColor = "89e051",
                "ShellCheck Config" => hexColor = "cecfcb",
                "Shen" => hexColor = "120F14",
                "Singularity" => hexColor = "64E6AD",
                "Slash" => hexColor = "007eff",
                "Slice" => hexColor = "003fa2",
                "Slim" => hexColor = "2b2b2b",
                "Smalltalk" => hexColor = "596706",
                "Smarty" => hexColor = "f0c040",
                "SmPL" => hexColor = "c94949",
                "Solidity" => hexColor = "AA6746",
                "SourcePawn" => hexColor = "f69e1d",
                "SPARQL" => hexColor = "0C4597",
                "SQF" => hexColor = "3F3F3F",
                "SQL" => hexColor = "e38c00",
                "SQLPL" => hexColor = "e38c00",
                "Squirrel" => hexColor = "800000",
                "SRecode Template" => hexColor = "348a34",
                "Stan" => hexColor = "b2011d",
                "Standard ML" => hexColor = "dc566d",
                "Starlark" => hexColor = "76d275",
                "Stata" => hexColor = "1a5f91",
                "StringTemplate" => hexColor = "3fb34f",
                "Stylus" => hexColor = "ff6347",
                "SubRip Text" => hexColor = "9e0101",
                "SugarSS" => hexColor = "2fcc9f",
                "SuperCollider" => hexColor = "46390b",
                "Svelte" => hexColor = "ff3e00",
                "SVG" => hexColor = "ff9900",
                "Swift" => hexColor = "F05138",
                "SystemVerilog" => hexColor = "DAE1C2",
                "Tcl" => hexColor = "e4cc98",
                "Terra" => hexColor = "00004c",
                "TeX" => hexColor = "3D6117",
                "Textile" => hexColor = "ffe7ac",
                "TextMate Properties" => hexColor = "df66e4",
                "Thrift" => hexColor = "D12127",
                "TI Program" => hexColor = "A0AA87",
                "TLA" => hexColor = "4b0079",
                "TOML" => hexColor = "9c4221",
                "TSQL" => hexColor = "e38c00",
                "TSV" => hexColor = "237346",
                "TSX" => hexColor = "2b7489",
                "Turing" => hexColor = "cf142b",
                "Twig" => hexColor = "c1d026",
                "TXL" => hexColor = "0178b8",
                "TypeScript" => hexColor = "2b7489",
                "Unified Parallel C" => hexColor = "4e3617",
                "Unity3D Asset" => hexColor = "222c37",
                "Uno" => hexColor = "9933cc",
                "UnrealScript" => hexColor = "a54c4d",
                "UrWeb" => hexColor = "ccccee",
                "V" => hexColor = "4f87c4",
                "Vala" => hexColor = "fbe5cd",
                "Valve Data Format" => hexColor = "f26025",
                "VBA" => hexColor = "867db1",
                "VBScript" => hexColor = "15dcdc",
                "VCL" => hexColor = "148AA8",
                "Verilog" => hexColor = "b2b7f8",
                "VHDL" => hexColor = "adb2cb",
                "Vim Help File" => hexColor = "199f4b",
                "Vim Script" => hexColor = "199f4b",
                "Vim Snippet" => hexColor = "199f4b",
                "Visual Basic .NET" => hexColor = "945db7",
                "Volt" => hexColor = "1F1F1F",
                "Vue" => hexColor = "41b883",
                "wdl" => hexColor = "42f1f4",
                "Web Ontology Language" => hexColor = "5b70bd",
                "WebAssembly" => hexColor = "04133b",
                "Wikitext" => hexColor = "fc5757",
                "Windows Registry Entries" => hexColor = "52d5ff",
                "wisp" => hexColor = "7582D1",
                "Wollok" => hexColor = "a23738",
                "World of Warcraft Addon Data" => hexColor = "f7e43f",
                "X10" => hexColor = "4B6BEF",
                "xBase" => hexColor = "403a40",
                "XC" => hexColor = "99DA07",
                "XML" => hexColor = "0060ac",
                "XML Property List" => hexColor = "0060ac",
                "Xojo" => hexColor = "81bd41",
                "Xonsh" => hexColor = "285EEF",
                "XQuery" => hexColor = "5232e7",
                "XSLT" => hexColor = "EB8CEB",
                "Xtend" => hexColor = "24255d",
                "Yacc" => hexColor = "4B6C4B",
                "YAML" => hexColor = "cb171e",
                "YARA" => hexColor = "220000",
                "YASnippet" => hexColor = "32AB90",
                "ZAP" => hexColor = "0d665e",
                "ZenScript" => hexColor = "00BCD1",
                "Zephir" => hexColor = "118F9E",
                "Zig" => hexColor = "EC915C",
                "ZIL" => hexColor = "DC75E5",
                "Zimpl" => hexColor = "D67711",
                _ => null,
            };
            #endregion

            return new SolidColorBrush(Color.FromArgb(
                0xFF,
                Convert.ToByte(hexColor.Substring(0, 2), 16),
                Convert.ToByte(hexColor.Substring(2, 2), 16),
                Convert.ToByte(hexColor.Substring(4, 2), 16)));
        }
    }
}
