pr:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - doc/*
      - samples/*
      - tools/*

name: $(Date:yyMM).$(Date:dd)$(Rev:rr)

variables:
- group: BuildPipelineVariables
- name: solution
  value: '**/*.sln'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'

stages:
  - stage: Build_Debug_x64
    displayName: Build Debug x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Release
          branding: Dev
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
          msBuildArgs: '
            /p:GenerateAppInstallerFile=True
            /p:AppxLogTelemetryFromSideloadingScript=False
            /p:AppInstallerUri=$(build.artifactstagingdirectory)
            /p:AppxBundlePlatforms="$(buildPlatform)"
            /p:AppxPackageDir="$(appxPackageDir)"
            /p:AppxBundle=Always
            /p:UapAppxPackageBuildMode=${{ parameters.configuration }}
            /p:AppxPackageSigningEnabled=true
            /p:PackageCertificateThumbprint=""
            /p:PackageCertificateKeyFile="$(caCertificate.secureFilePath)"
            /p:PackageCertificatePassword="$(signingCert.password)"'

  - stage: Build_Sideload_x64
    displayName: Build Sideload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Sideload
          branding: Beta
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
          msBuildArgs: '
            /p:AppInstallerUri="$(build.artifactstagingdirectory)"
            /p:AppxBundlePlatforms="$(buildPlatform)"
            /p:AppxPackageDir="$(appxPackageDir)"
            /p:UapAppxPackageBuildMode=${{ parameters.configuration }}
            /p:AppxPackageSigningEnabled=true
            /p:PackageCertificateThumbprint=""
            /p:PackageCertificateKeyFile="$(caCertificate.secureFilePath)"
            /p:PackageCertificatePassword="$(signingCert.password)"'

  - stage: Build_StoreUpload_x64
    displayName: Build StoreUpload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Release
          branding: Beta
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
          msBuildArgs: '
            /p:AppInstallerUri="$(build.artifactstagingdirectory)"
            /p:AppxBundlePlatforms="$(buildPlatform)"
            /p:AppxPackageDir="$(appxPackageDir)"
            /p:UapAppxPackageBuildMode=${{ parameters.configuration }}'
