pr:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - doc/*
      - samples/*
      - tools/*

name: $(Date:yyMM).$(Date:dd)$(Rev:rr)

stages:
  - stage: Build_Debug_x64
    displayName: Build Debug x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Debug
          branding: Dev
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'

  - stage: Build_Sideload_x64
    displayName: Build Sideload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Sideload
          branding: Beta
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'

- stage: Build_StoreUpload_x64
    displayName: Build StoreUpload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Release
          branding: Beta
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
