pr:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - doc/*
      - samples/*
      - tools/*

name: $(Date:yyMM).$(Date:dd)$(Rev:rr)

stages:
  - stage: Build_Debug_x64
    displayName: Build Debug x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: 'x64'
          configuration: 'Release'
          branding: 'Dev'
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
          buildArgs: '/p:GenerateAppInstallerFile=True /p:AppxLogTelemetryFromSideloadingScript=False /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Release /p:AppxPackageSigningEnabled=true'

  - stage: Build_Sideload_x64
    displayName: Build Sideload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: 'x64'
          configuration: 'Sideload'
          branding: 'Beta'
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
          buildArgs: '/p:UapAppxPackageBuildMode=Sideload /p:AppxPackageSigningEnabled=true'

  - stage: Build_StoreUpload_x64
    displayName: Build StoreUpload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: 'x64'
          configuration: 'Release'
          branding: 'Beta'
          identityName: 'FluentHubCI'
          identityPublisher: 'CN=FluentHubCI'
          displayName: 'FluentHub'
          visualDisplayName: 'FluentHub'
          buildArgs: '/p:UapAppxPackageBuildMode=StoreUpload'
