trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - doc/*
      - samples/*
      - tools/*

pr: none

name: $(Date:yyMM).$(Date:dd)$(Rev:rr)

variables:
- group: BuildPipelineVariables
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfigurationRelease
  value: 'Release'
- name: buildConfigurationSideload
  value: 'Sideload'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'

stages:
  - stage: Build_Debug_x64
    displayName: Build Debug x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Debug
          branding: Dev

  - stage: Build_Sideload_x64
    displayName: Build Sideload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Sideload
          branding: Beta

  - stage: Build_StoreUpload_x64
    displayName: Build StoreUpload x64
    dependsOn: []
    condition: succeeded()
    jobs:
      - template: ./templates/build-ci.yml
        parameters:
          platform: x64
          configuration: Release
          branding: Beta
