<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>Octokit.Transport</AssemblyName>
		<RootNamespace>Octokit.Transport</RootNamespace>
		<IsAotCompatible>true</IsAotCompatible>
		<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

</Project>
