<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>Octokit</AssemblyName>
		<RootNamespace>Octokit</RootNamespace>
		<IsAotCompatible>true</IsAotCompatible>
		<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<DefaultItemExcludes>$(DefaultItemExcludes);**/bin/**;**/obj/**</DefaultItemExcludes>
	</PropertyGroup>

</Project>
