# Copyright (c) 2024 0x5BFA
# Licensed under the MIT License. See the LICENSE.

name: FluentHub CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/assets/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/assets/**'
      - 'docs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'FluentHub PR Validation' || 'FluentHub CI Validation' }}

env:
  WORKING_DIR:                   '${{ github.workspace }}' # Default: 'D:\a\FluentHub\FluentHub'
  APP_PACKAGE_DIR:               '${{ github.workspace }}\src\FluentHub.App\AppPackages\'
  APP_PROJECT_PATH:              '${{ github.workspace }}\src\FluentHub.App\FluentHub.App.csproj'
  APP_MANIFEST_PATH:             '${{ github.workspace }}\src\FluentHub.App\Package.appxmanifest'
  APP_CREDENTIALS_PATH:          '${{ github.workspace }}\src\FluentHub.App\AppCredentials.config'

jobs:
  build:
    if: github.repository_owner == '0x5bfa'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build FluentHub
      run: |
        $bytes = [Convert]::FromBase64String($env:GH_CREDENTIALS_SECRET)
        [IO.File]::WriteAllBytes($env:APP_CREDENTIALS_PATH, $bytes)

        cd $env:WORKING_DIR\src

        & "$env:WORKING_DIR\.github\scripts\Build-App.ps1" `
          -Platform $env:PLATFORM `
          -Configuration $env:CONFIGURATION `
          -PackageManifestPath $env:APP_MANIFEST_PATH
      env:
        GH_CREDENTIALS_SECRET: '${{ secrets.GH_CREDENTIALS_JSON_BASE64 }}'

    - name: Upload the packages to the Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'Appx Packages (${{ env.CONFIGURATION }}, ${{ env.PLATFORM }})'
        path: ${{ env.APP_PACKAGE_DIR }}
