
name: UWP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [x64]
    steps:
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"


      - name: Checkout
        uses: actions/checkout@v2.3.4


      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2


      - name: Build UWP utilities
        run: msbuild /m /t:FluentHub /restore /p:Platform=${{ matrix.architecture }} /p:AppxBundle=$env:AppxBundle /p:AppxBundlePlatforms="${{ matrix.architecture }}" /p:AppxPackageDir=${{ github.workspace }}\artifacts\win-${{ matrix.architecture }} /p:AppxPackageSigningEnabled=false /p:RuntimeIdentifier=win-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}\artifacts\win-${{ matrix.architecture }}/UWP /p:PublishSingleFile=true /p:Configuration=Release FluentHub.sln
        env:
          AppxBundle: Always
          BuildMode: SideloadOnly
          Configuration: Release


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: win-${{ matrix.architecture }}
          path: ${{ github.workspace }}/artifacts/win-${{ matrix.architecture }}
